<?php require __DIR__.'/_common.php'; ?>
<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title><?=e($businessName)?> - Pawn Entry</title><?php include('includes/links.php');require __DIR__.'/_style.php';?>
<style>
.item-box{position:relative;padding:14px;margin-bottom:12px;border:1px solid var(--line);border-radius:var(--radius);background:color-mix(in srgb,var(--muted) 4%,transparent)}.item-title{font-size:10px;font-weight:800;color:var(--primary-dark);text-transform:uppercase;margin-bottom:10px}.customer-search{position:relative}.customer-results{display:none;position:absolute;z-index:1000;top:100%;left:0;right:0;max-height:260px;overflow:auto;background:var(--card-bg);border:1px solid var(--line);border-radius:9px;box-shadow:0 12px 30px rgba(0,0,0,.12)}.customer-result{padding:10px 12px;border-bottom:1px solid var(--line);cursor:pointer}.customer-result:hover{background:var(--primary-soft)}.summary-line{display:flex;justify-content:space-between;gap:10px;padding:7px 0;border-bottom:1px dashed var(--line);font-size:11px}.loan-value{padding:14px;border-radius:10px;background:var(--primary-soft);text-align:center}.loan-value strong{display:block;font-size:25px;color:var(--primary-dark)}.theme-toast{position:fixed;right:18px;top:78px;z-index:20000;padding:11px 14px;border-radius:10px;color:#fff;font-size:11px;font-weight:600}.theme-toast-success{background:#168449}.theme-toast-error{background:#c0392b}
</style></head><body>
<?php include('includes/sidebar.php');?><main class="app-main"><?php include('includes/nav.php');?><div class="content-wrap">
<div class="page-card mb-3"><div class="page-head"><div><div class="page-title">New Pawn Entry</div><div class="small text-muted">Create a pawn loan with customer, item, rate and tenure calculations.</div></div><div class="d-flex gap-2"><a href="metal-rates.php" class="btn-soft">Metal Rates</a><a href="pawn-list.php" class="btn-soft">Pawn List</a></div></div></div>
<form id="pawnForm"><input type="hidden" name="action" value="create"><input type="hidden" name="csrf_token" value="<?=e($csrfToken)?>"><input type="hidden" name="pawn_no" id="pawnNoHidden"><input type="hidden" name="total_gross_weight" id="totalGrossInput"><input type="hidden" name="total_stone_weight" id="totalStoneInput"><input type="hidden" name="total_net_weight" id="totalNetInput"><input type="hidden" name="total_estimated_value" id="totalEstimatedInput">
<div class="row g-3"><div class="col-xl-9">
<div class="page-card mb-3"><div class="page-head"><div class="section-title">Basic Information</div></div><div class="card-body-x"><div class="row g-2">
<div class="col-md-3"><label class="small fw-bold">Pawn No</label><input id="pawnNo" class="form-control" readonly></div>
<div class="col-md-3"><label class="small fw-bold">Pawn Date</label><input type="date" name="pawn_date" id="pawnDate" class="form-control" value="<?=date('Y-m-d')?>" required></div>
<div class="col-md-3"><label class="small fw-bold">Category</label><select name="pawn_category_id" id="categorySelect" class="form-select" required><option value="">Loading...</option></select></div>
<div class="col-md-3"><label class="small fw-bold">Primary Metal</label><select name="primary_metal_id" id="primaryMetal" class="form-select"><option value="">Select metal</option></select></div>
<div class="col-md-3"><label class="small fw-bold">Loan Type</label><input name="loan_type" class="form-control" value="General"></div>
<div class="col-md-3"><label class="small fw-bold">Tenure Months</label><input type="number" min="1" name="tenure_months" id="tenureMonths" class="form-control" value="12" required></div>
<div class="col-md-3"><label class="small fw-bold">Due Date</label><input type="date" name="due_date" id="dueDate" class="form-control"></div>
<div class="col-md-3"><label class="small fw-bold">Interest Method</label><select name="interest_method" class="form-select"><option>Simple</option><option>Flat</option></select></div>
</div></div></div>
<div class="page-card mb-3"><div class="page-head"><div class="section-title">Customer Information</div></div><div class="card-body-x"><div class="row g-2">
<div class="col-12 customer-search"><label class="small fw-bold">Search Customer</label><input id="customerSearch" class="form-control" placeholder="Search name, code or mobile" autocomplete="off"><div id="customerResults" class="customer-results"></div></div>
<div class="col-md-4"><label class="small fw-bold">Existing Customer</label><select name="customer_id" id="customerSelect" class="form-select" required><option value="">Loading...</option></select></div>
<div class="col-md-4"><label class="small fw-bold">Name</label><input id="customerName" class="form-control" readonly></div>
<div class="col-md-4"><label class="small fw-bold">Mobile</label><input id="customerMobile" class="form-control" readonly></div>
<div class="col-md-4"><label class="small fw-bold">Email</label><input id="customerEmail" class="form-control" readonly></div>
<div class="col-md-4"><label class="small fw-bold">ID Proof Type</label><select name="id_proof_type" id="idProofType" class="form-select"><option value="">Select</option><option>Aadhar</option><option>PAN</option><option>Voter</option><option>Driving</option><option>Passport</option></select></div>
<div class="col-md-4"><label class="small fw-bold">ID Proof Number</label><input name="id_proof_number" id="idProofNumber" class="form-control"></div>
<div class="col-12"><label class="small fw-bold">Address</label><textarea id="customerAddress" class="form-control" rows="2" readonly></textarea></div>
</div></div></div>
<div class="page-card mb-3"><div class="page-head"><div class="section-title">Pawn Items</div><button type="button" class="btn-theme" id="addItemBtn">Add Item</button></div><div class="card-body-x" id="itemsWrap"></div></div>
<div class="page-card mb-3"><div class="page-head"><div class="section-title">Disbursement Details</div></div><div class="card-body-x"><div class="row g-2">
<div class="col-md-3"><label class="small fw-bold">Ticket Charge</label><input type="number" step="0.01" min="0" name="ticket_charge" class="form-control" value="0"></div>
<div class="col-md-3"><label class="small fw-bold">Other Charge</label><input type="number" step="0.01" min="0" name="other_charge" class="form-control" value="0"></div>
<div class="col-md-3"><label class="small fw-bold">Payment Method</label><select name="payment_method_id" id="paymentMethod" class="form-select"><option value="">Select Method</option></select></div>
<div class="col-md-3"><label class="small fw-bold">Payment Reference</label><input name="payment_reference" class="form-control"></div>
</div></div></div>
</div><div class="col-xl-3"><div class="page-card sticky-top" style="top:82px"><div class="page-head"><div class="section-title">Loan Details</div></div><div class="card-body-x">
<div class="loan-value mb-3"><span class="small text-muted">Calculated Loan Value</span><strong>₹<span id="calculatedLoan">0.00</span></strong></div>
<div class="mb-2"><label class="small fw-bold">Principal Amount</label><input type="number" step="0.01" min="0.01" name="principal_amount" id="principalAmount" class="form-control" required></div>
<div class="mb-2"><label class="small fw-bold">Interest %</label><input type="number" step="0.001" min="0" name="interest_percent" id="interestPercent" class="form-control" required></div>
<div class="mb-2"><label class="small fw-bold">Interest Period</label><select name="interest_period" class="form-select"><option>Monthly</option><option>Daily</option><option>Yearly</option></select></div>
<div class="mb-2"><label class="small fw-bold">Remarks</label><textarea name="remarks" class="form-control" rows="4"></textarea></div><hr>
<div class="summary-line"><span>Items</span><strong id="itemCount">0</strong></div><div class="summary-line"><span>Total Gross</span><strong id="totalGross">0.000 g</strong></div><div class="summary-line"><span>Total Stone/Less</span><strong id="totalStone">0.000 g</strong></div><div class="summary-line"><span>Total Net</span><strong id="totalNet">0.000 g</strong></div><div class="summary-line"><span>Estimated Value</span><strong>₹<span id="totalEstimated">0.00</span></strong></div>
<button type="submit" class="btn-theme w-100 mt-3" id="saveBtn">Save Pawn Entry</button></div></div></div></div></form>
<?php include('includes/footer.php');?></div></main><?php include('includes/script.php');?><script src="assets/js/script.js"></script>
<script>
(()=>{'use strict';const api='api/pawn-entry.php',csrf=<?=json_encode($csrfToken)?>;let data={customers:[],categories:[],metals:[],metal_rates:[],payment_methods:[]};
const $=id=>document.getElementById(id);function esc(v){return String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#039;','"':'&quot;'}[c]))}function money(v){return Number(v||0).toLocaleString('en-IN',{minimumFractionDigits:2,maximumFractionDigits:2})}function note(t,m){const x=document.createElement('div');x.className='theme-toast theme-toast-'+(t==='ok'?'success':'error');x.textContent=m;document.body.appendChild(x);setTimeout(()=>x.remove(),3200)}async function req(o){const f=new FormData();Object.entries(o).forEach(([k,v])=>f.append(k,v));f.append('csrf_token',csrf);const r=await fetch(api,{method:'POST',body:f,credentials:'same-origin',headers:{Accept:'application/json'}}),raw=await r.text();let j;try{j=JSON.parse(raw)}catch(e){throw new Error('Pawn Entry API did not return JSON. HTTP '+r.status+': '+raw.replace(/<[^>]*>/g,' ').slice(0,260))}if(!r.ok||!j.success)throw new Error(j.message||'Request failed');return j}
function metalOpts(sel=''){return data.metals.map(m=>`<option value="${m.id}" ${String(sel)===String(m.id)?'selected':''}>${esc(m.metal_name)}</option>`).join('')}function itemRow(){const pm=$('primaryMetal').value||'';return `<div class="item-box"><div class="item-title">Pawn Item</div><div class="row g-2"><div class="col-md-3"><label class="small fw-bold">Metal</label><select name="metal_id[]" class="form-select item-metal" required><option value="">Select metal</option>${metalOpts(pm)}</select></div><div class="col-md-4"><label class="small fw-bold">Description</label><input name="item_description[]" class="form-control" required></div><div class="col-md-2"><label class="small fw-bold">Qty</label><input type="number" min="1" name="quantity[]" class="form-control" value="1"></div><div class="col-md-3"><label class="small fw-bold">Purity</label><input name="purity[]" class="form-control item-purity" placeholder="916 / 22K"></div><div class="col-md-2"><label class="small fw-bold">Gross</label><input type="number" step="0.001" min="0" name="gross_weight[]" class="form-control calc gross" value="0"></div><div class="col-md-2"><label class="small fw-bold">Stone/Less</label><input type="number" step="0.001" min="0" name="stone_weight[]" class="form-control calc stone" value="0"></div><div class="col-md-2"><label class="small fw-bold">Net</label><input type="number" step="0.001" name="net_weight[]" class="form-control net" readonly></div><div class="col-md-2"><label class="small fw-bold">Rate / Gram</label><input type="number" step="0.01" min="0" name="rate_per_gram[]" class="form-control calc rate" value="0"></div><div class="col-md-2"><label class="small fw-bold">Estimated</label><input type="number" step="0.01" name="estimated_value[]" class="form-control est" readonly></div><div class="col-md-2 d-flex align-items-end"><button type="button" class="btn-soft remove-item w-100">Remove</button></div><div class="col-12"><label class="small fw-bold">Item Remarks</label><input name="item_remarks[]" class="form-control"></div></div></div>`}
function rateFor(mid,p){const exact=data.metal_rates.find(r=>String(r.metal_id||'')===String(mid||'')&&String(r.purity||'').toLowerCase()===String(p||'').trim().toLowerCase());const any=data.metal_rates.find(r=>String(r.metal_id||'')===String(mid||''));return Number((exact||any)?.rate_per_gram||0)}function updateRate(box){const r=box.querySelector('.rate');if(Number(r.value||0)<=0){const v=rateFor(box.querySelector('.item-metal').value,box.querySelector('.item-purity').value);if(v>0)r.value=v.toFixed(2)}totals()}function totals(){let g=0,s=0,n=0,v=0,c=0;document.querySelectorAll('.item-box').forEach((b,i)=>{b.querySelector('.item-title').textContent='Pawn Item '+(i+1);const gross=Number(b.querySelector('.gross').value||0),stone=Number(b.querySelector('.stone').value||0),net=Math.max(0,gross-stone),rate=Number(b.querySelector('.rate').value||0),est=net*rate;b.querySelector('.net').value=net.toFixed(3);b.querySelector('.est').value=est.toFixed(2);g+=gross;s+=stone;n+=net;v+=est;c++});$('itemCount').textContent=c;$('totalGross').textContent=g.toFixed(3)+' g';$('totalStone').textContent=s.toFixed(3)+' g';$('totalNet').textContent=n.toFixed(3)+' g';$('totalEstimated').textContent=money(v);$('calculatedLoan').textContent=money(v);$('totalGrossInput').value=g.toFixed(3);$('totalStoneInput').value=s.toFixed(3);$('totalNetInput').value=n.toFixed(3);$('totalEstimatedInput').value=v.toFixed(2);if(!$('principalAmount').dataset.manual)$('principalAmount').value=v>0?v.toFixed(2):''}
function due(){const d=$('pawnDate').value,t=Number($('tenureMonths').value||0);if(!d||t<=0)return;const x=new Date(d+'T00:00:00');x.setMonth(x.getMonth()+t);$('dueDate').value=x.getFullYear()+'-'+String(x.getMonth()+1).padStart(2,'0')+'-'+String(x.getDate()).padStart(2,'0')}function loadCustomer(id){const c=data.customers.find(x=>String(x.id)===String(id));$('customerName').value=c?.customer_name||'';$('customerMobile').value=c?.mobile||'';$('customerEmail').value=c?.email||'';$('customerAddress').value=[c?.address_line1,c?.address_line2,c?.city,c?.state,c?.pincode].filter(Boolean).join(', ');$('idProofType').value=c?.id_proof_type||'';$('idProofNumber').value=c?.id_proof_number||''}
function searchCustomers(q){const box=$('customerResults'),t=q.trim().toLowerCase();if(t.length<2){box.style.display='none';return}const rows=data.customers.filter(c=>String(c.customer_name||'').toLowerCase().includes(t)||String(c.customer_code||'').toLowerCase().includes(t)||String(c.mobile||'').includes(t)).slice(0,20);box.innerHTML=rows.length?rows.map(c=>`<div class="customer-result" data-id="${c.id}"><strong>${esc(c.customer_name)}</strong><div class="small text-muted">${esc(c.customer_code)} · ${esc(c.mobile||'')}</div></div>`).join(''):'<div class="p-3 text-center text-muted">No customer found.</div>';box.style.display='block'}
async function init(){try{data=await req({action:'options'});$('pawnNo').value=data.next_pawn_no;$('pawnNoHidden').value=data.next_pawn_no;$('categorySelect').innerHTML='<option value="">Select category</option>'+data.categories.map(c=>`<option value="${c.id}" data-interest="${c.default_interest_percent||0}" data-metal="${esc(c.metal_type||'')}" data-purity="${esc(c.purity_standard||'')}">${esc(c.category_name)}</option>`).join('');$('customerSelect').innerHTML='<option value="">Select customer</option>'+data.customers.map(c=>`<option value="${c.id}">${esc(c.customer_name)} - ${esc(c.customer_code)} - ${esc(c.mobile||'')}</option>`).join('');$('primaryMetal').innerHTML='<option value="">Select metal</option>'+metalOpts();$('paymentMethod').innerHTML='<option value="">Select Method</option>'+data.payment_methods.map(m=>`<option value="${m.id}">${esc(m.method_name)}</option>`).join('');$('itemsWrap').innerHTML=itemRow();due();totals()}catch(e){note('bad',e.message)}}
$('addItemBtn').onclick=()=>{$('itemsWrap').insertAdjacentHTML('beforeend',itemRow());totals()};document.addEventListener('input',e=>{if(e.target.classList.contains('calc'))totals();if(e.target.classList.contains('item-purity'))updateRate(e.target.closest('.item-box'))});document.addEventListener('change',e=>{if(e.target.classList.contains('item-metal')||e.target.classList.contains('item-purity'))updateRate(e.target.closest('.item-box'))});document.addEventListener('click',e=>{const rm=e.target.closest('.remove-item');if(rm){if(document.querySelectorAll('.item-box').length===1)return note('bad','At least one item is required.');rm.closest('.item-box').remove();totals();return}const cr=e.target.closest('.customer-result');if(cr){$('customerSelect').value=cr.dataset.id;loadCustomer(cr.dataset.id);$('customerSearch').value='';$('customerResults').style.display='none'}});$('customerSearch').oninput=e=>searchCustomers(e.target.value);$('customerSelect').onchange=e=>loadCustomer(e.target.value);$('pawnDate').onchange=due;$('tenureMonths').oninput=due;$('principalAmount').oninput=e=>e.target.dataset.manual='1';$('primaryMetal').onchange=e=>{document.querySelectorAll('.item-metal').forEach(s=>{if(!s.value)s.value=e.target.value});document.querySelectorAll('.item-box').forEach(updateRate)};$('categorySelect').onchange=e=>{const o=e.target.options[e.target.selectedIndex];$('interestPercent').value=o?.dataset.interest||'';const m=data.metals.find(x=>String(x.metal_name||'').toLowerCase()===String(o?.dataset.metal||'').toLowerCase());if(m){$('primaryMetal').value=m.id;document.querySelectorAll('.item-metal').forEach(s=>{if(!s.value)s.value=m.id})}if(o?.dataset.purity)document.querySelectorAll('.item-purity').forEach(i=>{if(!i.value)i.value=o.dataset.purity});document.querySelectorAll('.item-box').forEach(updateRate)};
$('pawnForm').onsubmit=async e=>{e.preventDefault();totals();if(!$('customerSelect').value)return note('bad','Select a customer.');if(Number($('totalNetInput').value||0)<=0)return note('bad','Total net weight must be greater than zero.');if(Number($('principalAmount').value||0)<=0)return note('bad','Principal amount must be greater than zero.');const b=$('saveBtn'),old=b.innerHTML;b.disabled=true;b.innerHTML='Saving...';try{const r=await fetch(api,{method:'POST',body:new FormData(e.target),credentials:'same-origin',headers:{Accept:'application/json'}}),raw=await r.text();let j;try{j=JSON.parse(raw)}catch(x){throw new Error(raw.slice(0,300))}if(!r.ok||!j.success)throw new Error(j.message||'Unable to save');note('ok',j.message);setTimeout(()=>location.href='pawn-view.php?id='+j.pawn_id,600)}catch(err){note('bad',err.message)}finally{b.disabled=false;b.innerHTML=old}};init()})();
</script></body></html>
