<?php require __DIR__ . '/_common.php'; ?>
<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title><?=e($businessName)?> - Pawn Collections</title><?php include('includes/links.php'); require __DIR__.'/_style.php';?>
<style>
.stats{display:grid;grid-template-columns:repeat(5,minmax(0,1fr));gap:10px;margin-bottom:12px}.stat{padding:13px 14px;border:1px solid var(--line);border-radius:var(--radius);background:var(--card-bg)}.stat span{font-size:9px;color:var(--muted);text-transform:uppercase}.stat strong{display:block;margin-top:3px;font-size:20px}.filters{display:grid;grid-template-columns:minmax(220px,1.4fr) repeat(3,minmax(145px,.7fr)) auto;gap:8px}.compact-table{font-size:10px;margin:0}.compact-table th{font-size:9px;text-transform:uppercase;color:var(--muted);background:color-mix(in srgb,var(--muted) 5%,transparent);white-space:nowrap}.compact-table td,.compact-table th{padding:9px 10px;vertical-align:middle;border-color:var(--line)}.badge-x{display:inline-flex;padding:4px 7px;border-radius:999px;font-size:9px;font-weight:800}.interest{background:#eef6ff;color:#1f6fb2}.payment{background:#edf8f1;color:#168449}.reversed{background:#fff0ef;color:#c0392b}.toast-x{position:fixed;right:18px;top:78px;z-index:20000;padding:11px 14px;border-radius:10px;color:#fff;font-size:11px;background:#c0392b}@media(max-width:1100px){.stats{grid-template-columns:repeat(2,1fr)}.filters{grid-template-columns:1fr 1fr}.filters .search{grid-column:1/-1}}@media(max-width:600px){.stats,.filters{grid-template-columns:1fr}}
</style></head><body><?php include('includes/sidebar.php');?><main class="app-main"><?php include('includes/nav.php');?><div class="content-wrap">
<div class="page-card mb-3"><div class="page-head"><div><div class="page-title">Pawn Collections</div><div class="small text-muted">Combined interest, principal, part-payment and closure collection history.</div></div><div class="d-flex gap-2"><a href="pawn-interest.php" class="btn-soft">Collect Interest</a><a href="pawn-payment.php" class="btn-theme">New Payment</a></div></div></div>
<div class="stats"><div class="stat"><span>Records</span><strong id="statCount">0</strong></div><div class="stat"><span>Principal</span><strong>₹<span id="statPrincipal">0.00</span></strong></div><div class="stat"><span>Interest</span><strong>₹<span id="statInterest">0.00</span></strong></div><div class="stat"><span>Charges</span><strong>₹<span id="statCharges">0.00</span></strong></div><div class="stat"><span>Total Collected</span><strong>₹<span id="statTotal">0.00</span></strong></div></div>
<div class="page-card mb-3"><div class="card-body-x"><div class="filters"><input id="search" class="form-control search" placeholder="Search receipt, pawn no, customer or mobile"><input type="date" id="fromDate" class="form-control" value="<?=date('Y-m-01')?>"><input type="date" id="toDate" class="form-control" value="<?=date('Y-m-d')?>"><select id="collectionType" class="form-select"><option value="all">All Collections</option><option value="interest">Interest Collections</option><option value="payment">Pawn Payments</option></select><button id="refreshBtn" class="btn-soft">Refresh</button></div></div></div>
<div class="page-card"><div class="table-responsive"><table class="table compact-table"><thead><tr><th>Date</th><th>Receipt</th><th>Pawn / Customer</th><th>Type</th><th class="text-end">Principal</th><th class="text-end">Interest</th><th class="text-end">Penalty</th><th class="text-end">Other</th><th class="text-end">Total</th><th>Method</th></tr></thead><tbody id="rows"></tbody></table></div><div id="empty" class="text-center text-muted p-4 d-none">No collection records found for the selected period.</div></div>
<?php include('includes/footer.php');?></div></main><?php include('includes/script.php');?><script src="assets/js/script.js"></script>
<script>
(()=>{'use strict';const api='api/pawn-operations.php',csrf=<?=json_encode($csrfToken)?>,$=id=>document.getElementById(id);let timer;function money(v){return Number(v||0).toLocaleString('en-IN',{minimumFractionDigits:2,maximumFractionDigits:2})}function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]))}function toast(msg){const x=document.createElement('div');x.className='toast-x';x.textContent=msg;document.body.appendChild(x);setTimeout(()=>x.remove(),3000)}async function req(o){const f=new FormData();Object.entries(o).forEach(([k,v])=>f.append(k,v));f.append('csrf_token',csrf);const r=await fetch(api,{method:'POST',body:f,credentials:'same-origin'}),j=await r.json().catch(()=>({success:false,message:'Invalid server response.'}));if(!r.ok||!j.success)throw new Error(j.message||'Request failed');return j}
async function load(){try{const j=await req({action:'collections_list',search:$('search').value.trim(),from_date:$('fromDate').value,to_date:$('toDate').value,collection_type:$('collectionType').value});const rows=j.rows||[];$('rows').innerHTML=rows.map(x=>`<tr class="${Number(x.is_reversed)===1?'text-decoration-line-through opacity-50':''}"><td>${esc(x.record_date)}</td><td><strong>${esc(x.receipt_no)}</strong>${x.reference_no?`<div class="small text-muted">${esc(x.reference_no)}</div>`:''}</td><td><strong>${esc(x.pawn_no)}</strong><div class="small text-muted">${esc(x.customer_name)} · ${esc(x.mobile||'')}</div></td><td><span class="badge-x ${x.record_type==='Interest'?'interest':'payment'}">${esc(x.record_type)}</span><div class="small text-muted mt-1">${esc(x.detail_type||'')}</div></td><td class="text-end">₹${money(x.principal_amount)}</td><td class="text-end">₹${money(x.interest_amount)}</td><td class="text-end">₹${money(x.penalty_amount)}</td><td class="text-end">₹${money(x.other_charges)}</td><td class="text-end"><strong>₹${money(x.total_amount)}</strong></td><td>${esc(x.method_name||'—')}${Number(x.is_reversed)===1?'<div class="badge-x reversed mt-1">Reversed</div>':''}</td></tr>`).join('');$('empty').classList.toggle('d-none',rows.length>0);const s=j.summary||{};$('statCount').textContent=Number(s.count||0);$('statPrincipal').textContent=money(s.principal);$('statInterest').textContent=money(s.interest);$('statCharges').textContent=money(Number(s.penalty||0)+Number(s.other||0));$('statTotal').textContent=money(s.total)}catch(e){toast(e.message)}}
$('refreshBtn').onclick=load;$('fromDate').onchange=load;$('toDate').onchange=load;$('collectionType').onchange=load;$('search').oninput=()=>{clearTimeout(timer);timer=setTimeout(load,350)};load();})();
</script></body></html>
