<?php require __DIR__.'/_common.php'; ?>
<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title><?=e($businessName)?> - Pawn Entry</title><?php include('includes/links.php');require __DIR__.'/_style.php';?></head><body>
<?php include('includes/sidebar.php');?><main class="app-main"><?php include('includes/nav.php');?><div class="content-wrap">
<div class="page-card mb-3"><div class="page-head"><div><div class="page-title">New Pawn Entry</div><div class="small text-muted">Create a pawn loan using current categories, metals and customers.</div></div><a href="pawn-list.php" class="btn-soft">Pawn List</a></div></div>
<form id="pawnForm"><input type="hidden" name="action" value="create"><input type="hidden" name="csrf_token" value="<?=e($csrfToken)?>">
<div class="row g-3"><div class="col-xl-9">
<div class="page-card mb-3"><div class="page-head"><div class="section-title">Basic Information</div></div><div class="card-body-x"><div class="row g-2">
<div class="col-md-3"><label class="small fw-bold">Pawn No</label><input id="pawnNo" class="form-control" readonly></div><div class="col-md-3"><label class="small fw-bold">Pawn Date</label><input type="date" name="pawn_date" class="form-control" value="<?=date('Y-m-d')?>" required></div><div class="col-md-3"><label class="small fw-bold">Category</label><select name="pawn_category_id" id="categorySelect" class="form-select" required><option value="">Loading...</option></select></div><div class="col-md-3"><label class="small fw-bold">Due Date</label><input type="date" name="due_date" class="form-control"></div>
</div></div></div>
<div class="page-card mb-3"><div class="page-head"><div class="section-title">Customer Information</div></div><div class="card-body-x"><div class="row g-2"><div class="col-md-4"><label class="small fw-bold">Customer</label><select name="customer_id" id="customerSelect" class="form-select" required><option value="">Loading...</option></select></div><div class="col-md-4"><label class="small fw-bold">Name</label><input id="customerName" class="form-control" readonly></div><div class="col-md-4"><label class="small fw-bold">Mobile</label><input id="customerMobile" class="form-control" readonly></div><div class="col-12"><label class="small fw-bold">Address</label><textarea id="customerAddress" class="form-control" rows="2" readonly></textarea></div></div></div></div>
<div class="page-card mb-3"><div class="page-head"><div class="section-title">Pawn Items</div><button type="button" class="btn-theme" id="addItemBtn">Add Item</button></div><div class="card-body-x" id="itemsWrap"></div></div>
</div><div class="col-xl-3"><div class="page-card"><div class="page-head"><div class="section-title">Loan Details</div></div><div class="card-body-x"><div class="mb-2"><label class="small fw-bold">Principal Amount</label><input type="number" step="0.01" min="0.01" name="principal_amount" class="form-control" required></div><div class="mb-2"><label class="small fw-bold">Interest %</label><input type="number" step="0.001" min="0" name="interest_percent" id="interestPercent" class="form-control" required></div><div class="mb-2"><label class="small fw-bold">Interest Period</label><select name="interest_period" class="form-select"><option>Monthly</option><option>Daily</option><option>Yearly</option></select></div><div class="mb-2"><label class="small fw-bold">Remarks</label><textarea name="remarks" class="form-control" rows="3"></textarea></div><hr><div class="d-flex justify-content-between small"><span>Total Gross</span><strong id="totalGross">0.000 g</strong></div><div class="d-flex justify-content-between small mt-2"><span>Total Net</span><strong id="totalNet">0.000 g</strong></div><div class="d-flex justify-content-between small mt-2"><span>Estimated Value</span><strong>₹<span id="totalEstimated">0.00</span></strong></div><button type="submit" class="btn-theme w-100 mt-3" id="saveBtn">Save Pawn Entry</button></div></div></div></div></form>
<?php include('includes/footer.php');?></div></main><?php include('includes/script.php');?><script src="assets/js/script.js"></script>
<script>
(()=>{'use strict';const api='api/pawn.php',csrf=<?=json_encode($csrfToken)?>;let data={customers:[],categories:[],metals:[]};
function esc(v){return String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#039;','"':'&quot;'}[c]))}function note(t,m){const x=document.createElement('div');x.className='toastx '+(t==='ok'?'ok':'bad');x.textContent=m;document.body.appendChild(x);setTimeout(()=>x.remove(),3200)}async function req(o){const f=new FormData();Object.entries(o).forEach(([k,v])=>f.append(k,v));f.append('csrf_token',csrf);const r=await fetch(api,{method:'POST',body:f,credentials:'same-origin',headers:{Accept:'application/json'}}),raw=await r.text();let j;try{j=JSON.parse(raw)}catch(e){throw new Error('Pawn API did not return JSON. HTTP '+r.status+': '+raw.replace(/<[^>]*>/g,' ').slice(0,220))}if(!r.ok||!j.success)throw new Error(j.message||'Request failed');return j}
function row(){return `<div class="item-box"><div class="row g-2"><div class="col-md-3"><label class="small fw-bold">Metal</label><select name="metal_id[]" class="form-select" required><option value="">Select metal</option>${data.metals.map(m=>`<option value="${m.id}">${esc(m.metal_name)}</option>`).join('')}</select></div><div class="col-md-4"><label class="small fw-bold">Description</label><input name="item_description[]" class="form-control" required></div><div class="col-md-2"><label class="small fw-bold">Qty</label><input type="number" step="0.001" min="0.001" name="quantity[]" class="form-control" value="1"></div><div class="col-md-3"><label class="small fw-bold">Purity</label><input type="number" step="0.0001" min="0" name="purity[]" class="form-control"></div><div class="col-md-2"><label class="small fw-bold">Gross</label><input type="number" step="0.001" min="0" name="gross_weight[]" class="form-control calc gross"></div><div class="col-md-2"><label class="small fw-bold">Stone</label><input type="number" step="0.001" min="0" name="stone_weight[]" class="form-control calc stone"></div><div class="col-md-2"><label class="small fw-bold">Net</label><input type="number" step="0.001" name="net_weight[]" class="form-control net" readonly></div><div class="col-md-3"><label class="small fw-bold">Estimated Value</label><input type="number" step="0.01" min="0" name="estimated_value[]" class="form-control calc est"></div><div class="col-md-3 d-flex align-items-end"><button type="button" class="btn-soft remove w-100">Remove</button></div></div></div>`}
function totals(){let g=0,n=0,v=0;document.querySelectorAll('.item-box').forEach(b=>{const gross=Number(b.querySelector('.gross').value||0),stone=Number(b.querySelector('.stone').value||0),net=Math.max(0,gross-stone);b.querySelector('.net').value=net.toFixed(3);g+=gross;n+=net;v+=Number(b.querySelector('.est').value||0)});totalGross.textContent=g.toFixed(3)+' g';totalNet.textContent=n.toFixed(3)+' g';totalEstimated.textContent=v.toFixed(2)}
async function init(){try{data=await req({action:'options'});pawnNo.value=data.next_pawn_no;categorySelect.innerHTML='<option value="">Select category</option>'+data.categories.map(c=>`<option value="${c.id}" data-interest="${c.default_interest_percent}">${esc(c.category_name)}</option>`).join('');customerSelect.innerHTML='<option value="">Select customer</option>'+data.customers.map(c=>`<option value="${c.id}">${esc(c.customer_name)} - ${esc(c.customer_code)} - ${esc(c.mobile||'')}</option>`).join('');itemsWrap.innerHTML=row()}catch(e){note('bad',e.message)}}
addItemBtn.onclick=()=>itemsWrap.insertAdjacentHTML('beforeend',row());document.addEventListener('input',e=>{if(e.target.classList.contains('calc'))totals()});document.addEventListener('click',e=>{if(e.target.classList.contains('remove')){if(document.querySelectorAll('.item-box').length===1)return note('bad','At least one item is required.');e.target.closest('.item-box').remove();totals()}});categorySelect.onchange=e=>interestPercent.value=e.target.options[e.target.selectedIndex]?.dataset.interest||'';customerSelect.onchange=e=>{const c=data.customers.find(x=>String(x.id)===String(e.target.value));customerName.value=c?.customer_name||'';customerMobile.value=c?.mobile||'';customerAddress.value=[c?.address_line1,c?.address_line2,c?.city,c?.state,c?.pincode].filter(Boolean).join(', ')};
pawnForm.onsubmit=async e=>{e.preventDefault();saveBtn.disabled=true;try{const r=await fetch(api,{method:'POST',body:new FormData(pawnForm),credentials:'same-origin',headers:{Accept:'application/json'}}),raw=await r.text();let j;try{j=JSON.parse(raw)}catch(x){throw new Error(raw.slice(0,220))}if(!r.ok||!j.success)throw new Error(j.message||'Unable to save');note('ok',j.message);setTimeout(()=>location.href='pawn-view.php?id='+j.pawn_id,500)}catch(err){note('bad',err.message)}finally{saveBtn.disabled=false}};init()})();
</script></body></html>
