<?php
if (session_status() === PHP_SESSION_NONE) session_start();
date_default_timezone_set((string)($_SESSION['timezone'] ?? 'Asia/Kolkata'));
foreach ([__DIR__.'/config/config.php',__DIR__.'/config.php',__DIR__.'/includes/config.php',__DIR__.'/super-admin/includes/config.php'] as $f){if(is_file($f)){require_once $f;break;}}
if(!isset($conn)||!($conn instanceof mysqli)) die('Database configuration is not available.');
mysqli_report(MYSQLI_REPORT_OFF);$conn->set_charset('utf8mb4');
function h($v):string{return htmlspecialchars((string)($v??''),ENT_QUOTES,'UTF-8');}
function tableExists(mysqli $c,string $t):bool{$s=$c->real_escape_string($t);$r=$c->query("SHOW TABLES LIKE '{$s}'");return $r&&$r->num_rows>0;}
if(empty($_SESSION['user_id'])){header('Location: login.php');exit;}
$businessId=(int)($_SESSION['business_id']??0);if($businessId<=0)die('A valid business must be selected.');
$pageTitle=$page_title='Pawn Report';$currentPage='pawn-reports';
$theme=['primary_color'=>'#d89416','primary_dark_color'=>'#b86a0b','primary_soft_color'=>'#fff6e5','sidebar_gradient_1'=>'#171c21','sidebar_gradient_2'=>'#20272d','sidebar_gradient_3'=>'#101419','page_background'=>'#f4f3f0','card_background'=>'#fff','text_color'=>'#171717','muted_text_color'=>'#7d8794','border_color'=>'#e8e8e8','font_family'=>'Inter','heading_font_family'=>'Playfair Display','border_radius_px'=>12];
if(tableExists($conn,'business_theme_settings')){$s=$conn->prepare('SELECT * FROM business_theme_settings WHERE business_id=? LIMIT 1');if($s){$s->bind_param('i',$businessId);$s->execute();$row=$s->get_result()->fetch_assoc()?:[];$s->close();foreach($theme as $k=>$v)if(isset($row[$k])&&$row[$k]!=='')$theme[$k]=$row[$k];}}
$businessName=(string)($_SESSION['business_name']??'Jewellery ERP');
?>
<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title><?=h($businessName)?> - Pawn Report</title><?php include 'includes/links.php'; ?>
<style>
:root{--primary:<?=h($theme['primary_color'])?>;--primary-dark:<?=h($theme['primary_dark_color'])?>;--primary-soft:<?=h($theme['primary_soft_color'])?>;--page-bg:<?=h($theme['page_background'])?>;--card-bg:<?=h($theme['card_background'])?>;--text:<?=h($theme['text_color'])?>;--muted:<?=h($theme['muted_text_color'])?>;--border:<?=h($theme['border_color'])?>;--radius:<?=(int)$theme['border_radius_px']?>px}
body{background:var(--page-bg);color:var(--text);font-family:<?=json_encode($theme['font_family'])?>,sans-serif}.sidebar{background:linear-gradient(180deg,<?=h($theme['sidebar_gradient_1'])?>,<?=h($theme['sidebar_gradient_2'])?>,<?=h($theme['sidebar_gradient_3'])?>)!important}
.stats{display:grid;grid-template-columns:repeat(4,1fr);gap:8px;margin-bottom:10px}.stat,.panel,.mini{background:var(--card-bg);border:1px solid var(--border);border-radius:var(--radius)}.stat{padding:13px;display:flex;gap:12px;align-items:center;min-height:82px}.icon{width:42px;height:42px;display:grid;place-items:center;border-radius:10px;background:var(--primary-soft);color:var(--primary-dark)}.label{font-size:10px;color:var(--muted)}.value{font-size:21px;font-weight:800;margin-top:4px}.panel{overflow:hidden;margin-bottom:10px}.ph{padding:11px 13px;border-bottom:1px solid var(--border);display:flex;justify-content:space-between;align-items:center;gap:10px}.pt{font-size:12px;font-weight:800}.ps{font-size:9px;color:var(--muted);margin-top:2px}.pb{padding:12px}.grid{display:grid;grid-template-columns:repeat(12,1fr);gap:10px}.s2{grid-column:span 2}.s3{grid-column:span 3}.s1{grid-column:span 1}.s12{grid-column:span 12}.fl{font-size:9px;text-transform:uppercase;font-weight:700;color:var(--muted);margin-bottom:4px}.form-control,.form-select{min-height:36px;font-size:10px;border-radius:9px;border-color:var(--border);background:var(--card-bg);color:var(--text)}.btn-theme{background:linear-gradient(135deg,var(--primary),var(--primary-dark));border:0;color:#fff;border-radius:9px;font-size:10px;font-weight:700;min-height:36px}.btn-lightx{border:1px solid var(--border);background:var(--card-bg);color:var(--text);border-radius:9px;font-size:10px;font-weight:700;min-height:36px;padding:8px 12px}.minis{display:grid;grid-template-columns:repeat(4,1fr);gap:8px;margin-bottom:10px}.mini{padding:11px 13px;display:flex;justify-content:space-between;font-size:10px}.mini span{color:var(--muted)}.table{font-size:10px;min-width:1450px;margin:0}.table th{font-size:9px;text-transform:uppercase;color:var(--muted);background:#f7f8fa;padding:10px;white-space:nowrap}.table td{padding:10px;vertical-align:middle;white-space:nowrap}.badge-status{padding:4px 8px;border-radius:999px;font-size:8px;font-weight:800}.active{background:#eaf8f0;color:#168449}.partial{background:#fff6df;color:#a66800}.closed{background:#eef2f6;color:#5d6874}.overdue{background:#fdecec;color:#bd2d2d}.actions{display:flex;gap:6px}.ab{width:32px;height:32px;display:grid;place-items:center;border:1px solid var(--border);border-radius:8px;color:var(--text);text-decoration:none}.state{padding:42px;text-align:center;color:var(--muted)}.toastx{position:fixed;right:18px;top:78px;z-index:99999;background:#c0392b;color:#fff;padding:11px 14px;border-radius:10px;font-size:11px;box-shadow:0 14px 35px #0003}
@media(max-width:1199px){.stats,.minis{grid-template-columns:repeat(2,1fr)}.grid{grid-template-columns:repeat(2,1fr)}.s1,.s2,.s3,.s12{grid-column:span 1}}@media(max-width:991px){.responsive{min-width:0}.responsive thead,.responsive tfoot{display:none}.responsive tbody{display:grid;grid-template-columns:repeat(2,1fr);gap:10px;padding:10px}.responsive tr{display:grid;grid-template-columns:1fr 1fr;border:1px solid var(--border);border-radius:var(--radius);padding:12px}.responsive td{display:flex;justify-content:space-between;white-space:normal;border:0;border-bottom:1px dashed var(--border);padding:8px 0}.responsive td:before{content:attr(data-label);font-size:8px;font-weight:700;color:var(--muted);text-transform:uppercase}.actions{justify-content:flex-start}}@media(max-width:767px){.stats,.minis,.grid{grid-template-columns:1fr}.responsive tbody{grid-template-columns:1fr}.responsive tr{grid-template-columns:1fr}.responsive td{grid-column:1/-1}.ph{align-items:flex-start;flex-direction:column}}
</style></head><body><?php include 'includes/sidebar.php'; ?><main class="app-main"><?php include 'includes/nav.php'; ?><div class="content-wrap">
<div class="stats"><div class="stat"><div class="icon"><i class="fa-solid fa-gem"></i></div><div><div class="label">Total Pawn Records</div><div class="value" id="totalRecords">0</div></div></div><div class="stat"><div class="icon"><i class="fa-solid fa-indian-rupee-sign"></i></div><div><div class="label">Principal Amount</div><div class="value" id="principal">₹0.00</div></div></div><div class="stat"><div class="icon"><i class="fa-solid fa-coins"></i></div><div><div class="label">Interest Collected</div><div class="value" id="interest">₹0.00</div></div></div><div class="stat"><div class="icon"><i class="fa-solid fa-wallet"></i></div><div><div class="label">Balance Principal</div><div class="value" id="balance">₹0.00</div></div></div></div>
<div class="panel"><div class="ph"><div><div class="pt">Pawn Report Filters</div><div class="ps">Filter by date, customer, category, status, and keyword.</div></div><div class="d-flex gap-2"><button class="btn btn-lightx" id="printBtn"><i class="fa-solid fa-print me-1"></i>Print</button><button class="btn btn-lightx" id="excelBtn"><i class="fa-solid fa-file-excel me-1"></i>Excel</button></div></div><div class="pb"><form id="filterForm" class="grid"><div class="s2"><div class="fl">From Date</div><input type="date" name="from_date" class="form-control"></div><div class="s2"><div class="fl">To Date</div><input type="date" name="to_date" class="form-control"></div><div class="s3"><div class="fl">Customer</div><select name="customer_id" id="customer" class="form-select"><option value="0">All Customers</option></select></div><div class="s2"><div class="fl">Status</div><select name="status" class="form-select"><option value="">All Status</option><option>Draft</option><option>Active</option><option>Partially Paid</option><option>Closed</option><option>Auctioned</option><option>Cancelled</option></select></div><div class="s2"><div class="fl">Search</div><input type="search" name="search" class="form-control" placeholder="Pawn no, customer, mobile"></div><div class="s1 d-flex align-items-end"><button class="btn btn-theme w-100"><i class="fa-solid fa-filter me-1"></i>Apply</button></div><div class="s12"><button type="button" class="btn btn-lightx" id="resetBtn">Reset Filters</button></div></form></div></div>
<div class="minis"><div class="mini"><span>Gross Weight</span><strong id="gross">0.000 g</strong></div><div class="mini"><span>Net Weight</span><strong id="net">0.000 g</strong></div><div class="mini"><span>Principal Paid</span><strong id="paid">₹0.00</strong></div><div class="mini"><span>Estimated Interest</span><strong id="estimated">₹0.00</strong></div></div>
<div class="panel"><div class="ph"><div><div class="pt">Pawn Details</div><div class="ps" id="period">Loading...</div></div><button class="btn btn-lightx" id="refresh"><i class="fa-solid fa-rotate"></i></button></div><div id="loading" class="state"><i class="fa-solid fa-spinner fa-spin"></i><div>Loading pawn report...</div></div><div id="wrap" class="table-responsive d-none"><table class="table responsive"><thead><tr><th>#</th><th>Pawn No</th><th>Date</th><th>Customer</th><th>Mobile</th><th>Category</th><th>Gross Wt</th><th>Net Wt</th><th>Principal</th><th>Interest %</th><th>Interest Paid</th><th>Principal Paid</th><th>Balance</th><th>Due Date</th><th>Status</th><th>Action</th></tr></thead><tbody id="body"></tbody><tfoot id="foot"></tfoot></table></div><div id="empty" class="state d-none">No pawn records found.</div></div>
<?php include 'includes/footer.php'; ?></div></main><?php include 'includes/script.php'; ?><script src="assets/js/script.js"></script><script>
(()=>{'use strict';const form=document.getElementById('filterForm'),body=document.getElementById('body'),foot=document.getElementById('foot'),wrap=document.getElementById('wrap'),loading=document.getElementById('loading'),empty=document.getElementById('empty'),customer=document.getElementById('customer');const money=v=>Number(v||0).toLocaleString('en-IN',{minimumFractionDigits:2,maximumFractionDigits:2});const esc=v=>{const d=document.createElement('div');d.textContent=v??'';return d.innerHTML};function toast(m){const e=document.createElement('div');e.className='toastx';e.textContent=m;document.body.appendChild(e);setTimeout(()=>e.remove(),3500)}async function req(u){const r=await fetch(u,{credentials:'same-origin',headers:{Accept:'application/json','X-Requested-With':'XMLHttpRequest'}}),t=await r.text();let j;try{j=JSON.parse(t)}catch{throw new Error(t?'Server returned invalid output: '+t.slice(0,180):'Empty server response')}if(!r.ok||!j.success)throw new Error(j.message||'Request failed');return j}
function summary(s){document.getElementById('totalRecords').textContent=Number(s.total_records||0);document.getElementById('principal').textContent='₹'+money(s.principal_amount);document.getElementById('interest').textContent='₹'+money(s.interest_collected);document.getElementById('balance').textContent='₹'+money(s.balance_principal);document.getElementById('gross').textContent=Number(s.gross_weight||0).toFixed(3)+' g';document.getElementById('net').textContent=Number(s.net_weight||0).toFixed(3)+' g';document.getElementById('paid').textContent='₹'+money(s.principal_paid);document.getElementById('estimated').textContent='₹'+money(s.estimated_interest)}
function render(rows,s){loading.classList.add('d-none');if(!rows.length){wrap.classList.add('d-none');empty.classList.remove('d-none');return}empty.classList.add('d-none');wrap.classList.remove('d-none');body.innerHTML=rows.map((r,i)=>{const st=String(r.status||'Active'),cl=st==='Active'?'active':st==='Partially Paid'?'partial':st==='Closed'||st==='Auctioned'?'closed':'overdue';return `<tr><td data-label="#">${i+1}</td><td data-label="Pawn No"><strong>${esc(r.pawn_no)}</strong></td><td data-label="Date">${esc(r.pawn_date_display)}</td><td data-label="Customer">${esc(r.customer_name||'—')}</td><td data-label="Mobile">${esc(r.mobile||'—')}</td><td data-label="Category">${esc(r.category_name||'—')}</td><td data-label="Gross Wt">${Number(r.total_gross_weight||0).toFixed(3)}</td><td data-label="Net Wt">${Number(r.total_net_weight||0).toFixed(3)}</td><td data-label="Principal">₹${money(r.principal_amount)}</td><td data-label="Interest %">${Number(r.interest_percent||0).toFixed(3)}%</td><td data-label="Interest Paid">₹${money(r.total_interest_collected)}</td><td data-label="Principal Paid">₹${money(r.total_principal_paid)}</td><td data-label="Balance">₹${money(r.balance_principal)}</td><td data-label="Due Date">${esc(r.due_date_display)}</td><td data-label="Status"><span class="badge-status ${cl}">${esc(st)}</span></td><td data-label="Action"><div class="actions"><a class="ab" href="pawn-view.php?id=${Number(r.id)}" title="View"><i class="fa-solid fa-eye"></i></a><a class="ab" href="pawn-payments.php?pawn_id=${Number(r.id)}" title="Payment"><i class="fa-solid fa-indian-rupee-sign"></i></a></div></td></tr>`}).join('');foot.innerHTML=`<tr><td colspan="6" class="text-end"><strong>Totals</strong></td><td><strong>${Number(s.gross_weight||0).toFixed(3)}</strong></td><td><strong>${Number(s.net_weight||0).toFixed(3)}</strong></td><td><strong>₹${money(s.principal_amount)}</strong></td><td></td><td><strong>₹${money(s.interest_collected)}</strong></td><td><strong>₹${money(s.principal_paid)}</strong></td><td><strong>₹${money(s.balance_principal)}</strong></td><td colspan="3"></td></tr>`}
async function bootstrap(){const j=await req('api/pawn-reports.php?action=bootstrap');customer.innerHTML='<option value="0">All Customers</option>'+j.customers.map(c=>`<option value="${c.id}">${esc(c.customer_name)}${c.customer_code?' ('+esc(c.customer_code)+')':''}</option>`).join('');form.from_date.value=j.defaults.from_date;form.to_date.value=j.defaults.to_date}
async function load(){loading.classList.remove('d-none');wrap.classList.add('d-none');empty.classList.add('d-none');try{const p=new URLSearchParams(new FormData(form));p.set('action','list');const j=await req('api/pawn-reports.php?'+p);summary(j.summary);render(j.rows,j.summary);document.getElementById('period').textContent='Period: '+j.period.from_display+' to '+j.period.to_display}catch(e){loading.classList.add('d-none');empty.classList.remove('d-none');empty.textContent=e.message;toast(e.message)}}
form.addEventListener('submit',e=>{e.preventDefault();load()});document.getElementById('resetBtn').onclick=async()=>{form.reset();await bootstrap();load()};document.getElementById('refresh').onclick=load;document.getElementById('printBtn').onclick=()=>window.print();document.getElementById('excelBtn').onclick=()=>{const p=new URLSearchParams(new FormData(form));p.set('action','export');location.href='api/pawn-reports.php?'+p};bootstrap().then(load).catch(e=>toast(e.message));})();
</script></body></html>
