<?php
header('Cache-Control: no-store, no-cache, must-revalidate, max-age=0');
header('Pragma: no-cache');
header('Expires: 0');
require __DIR__ . '/_common.php';
if (session_status() === PHP_SESSION_NONE) session_start();
if (empty($_SESSION['pawn_csrf'])) $_SESSION['pawn_csrf'] = bin2hex(random_bytes(24));
$csrfToken = (string)$_SESSION['pawn_csrf'];
$loanId = max(0,(int)($_GET['id'] ?? 0));
?>
<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title><?= e($businessName) ?> - <?= $loanId?'Edit':'Add' ?> Bank Pawn</title><?php include('includes/links.php'); require __DIR__ . '/_style.php'; ?>
<style>
.compact-head{padding:11px 13px!important}.compact-body{padding:12px 13px!important}.form-grid{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:8px}.span2{grid-column:span 2}.field-label{font-size:9px;font-weight:700;color:var(--muted);margin-bottom:4px;text-transform:uppercase}.item-table th{font-size:9px;text-transform:uppercase;color:var(--muted);white-space:nowrap}.item-table td{font-size:10px;vertical-align:middle}.mini-note{font-size:9px;color:var(--muted)}.summary-grid{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:7px}.summary-box{padding:9px 10px;border:1px solid var(--line);border-radius:10px;background:var(--card-bg)}.summary-box span{display:block;font-size:8px;text-transform:uppercase;color:var(--muted);margin-bottom:2px}.summary-box strong{font-size:12px}.lock-note{padding:9px 11px;border-radius:10px;border:1px solid #f0d9ae;background:#fff8ea;font-size:10px}.toast-x{position:fixed;right:18px;top:78px;z-index:20000;padding:10px 13px;border-radius:9px;color:#fff;font-size:11px;font-weight:700}.toast-x.ok{background:#168449}.toast-x.bad{background:#c0392b}@media(max-width:1100px){.form-grid,.summary-grid{grid-template-columns:repeat(2,1fr)}}@media(max-width:600px){.form-grid,.summary-grid{grid-template-columns:1fr}.span2{grid-column:1/-1}}
</style></head><body>
<?php include('includes/sidebar.php'); ?><main class="app-main"><?php include('includes/nav.php'); ?><div class="content-wrap">
<div class="page-card mb-3"><div class="page-head compact-head d-flex justify-content-between align-items-center flex-wrap gap-2"><div><div class="page-title" id="pageTitle"><?= $loanId?'Edit Bank Pawn':'Add Bank Pawn' ?></div><div class="small text-muted">Register bank re-pledge and link exact customer pawn gold items.</div></div><a href="pawn-bank.php" class="btn-soft"><i class="fa-solid fa-arrow-left"></i> Bank Pawns</a></div></div>
<div id="lockNote" class="lock-note mb-3 d-none"></div>
<form id="bankForm"><input type="hidden" name="loan_id" id="loanId" value="<?= (int)$loanId ?>">
<div class="page-card mb-3"><div class="page-head compact-head"><div class="section-title">Bank Loan Details</div></div><div class="card-body-x compact-body"><div class="form-grid">
<div><label class="field-label">Bank *</label><select name="bank_id" id="bankId" class="form-select financial" required><option value="">Select bank</option></select></div>
<div><label class="field-label">Bank Loan / Pledge No *</label><input name="bank_loan_no" id="bankLoanNo" class="form-control financial" maxlength="120" required></div>
<div><label class="field-label">Pledge Date *</label><input type="date" name="pledge_date" id="pledgeDate" class="form-control financial" value="<?= date('Y-m-d') ?>" required></div>
<div><label class="field-label">Bank Principal Received *</label><input type="number" min="0.01" step="0.01" name="principal_amount" id="bankPrincipal" class="form-control financial" required></div>
<div><label class="field-label">Bank Interest % *</label><input type="number" min="0" max="100" step="0.001" name="bank_interest_percent" id="bankRate" class="form-control financial" required></div>
<div><label class="field-label">Rate Period *</label><select name="bank_interest_period" id="bankPeriod" class="form-select financial"><option>Yearly</option><option>Monthly</option><option>Daily</option></select></div>
<div><label class="field-label">Interest Method *</label><select name="bank_interest_method" id="bankMethod" class="form-select financial"><option>Simple</option><option>Reducing Balance</option><option>Flat</option></select></div>
<div><label class="field-label">Interest Payable *</label><select name="interest_payment_cycle" id="payCycle" class="form-select financial"><option>Yearly</option><option>Monthly</option><option>Quarterly</option><option>Half-Yearly</option><option>At Closure</option><option>Custom</option></select></div>
<div id="customMonthsWrap" class="d-none"><label class="field-label">Custom Cycle Months</label><input type="number" min="1" max="120" name="interest_cycle_months" id="cycleMonths" class="form-control financial" value="12"></div>
<div><label class="field-label">Maturity Date</label><input type="date" name="maturity_date" id="maturityDate" class="form-control"></div>
<div><label class="field-label">Bank Document No</label><input name="bank_document_no" id="bankDocumentNo" class="form-control" maxlength="150"></div>
<div class="span2"><label class="field-label">Remarks</label><input name="remarks" id="remarks" class="form-control" maxlength="500" placeholder="Optional bank loan remarks"></div>
</div></div></div>
<div class="page-card mb-3"><div class="page-head compact-head d-flex justify-content-between align-items-center flex-wrap gap-2"><div><div class="section-title">Select Customer Pawn Gold</div><div class="mini-note">Shows customer name, mobile and exact pawn item. Items pledged to another active bank loan are excluded.</div></div><div class="d-flex gap-2"><input id="searchItems" class="form-control form-control-sm" style="width:270px" placeholder="Search pawn / customer / mobile / item"><button type="button" class="btn-soft btn-sm" id="selectAllBtn">Select All</button></div></div><div class="table-responsive"><table class="table item-table mb-0"><thead><tr><th style="width:36px"></th><th>Pawn / Customer</th><th>Item</th><th>Metal</th><th>Qty</th><th>Gross g</th><th>Stone g</th><th>Net g</th><th>Estimated</th><th style="width:155px">Bank Principal Allocation</th></tr></thead><tbody id="itemBody"><tr><td colspan="10" class="text-center text-muted p-4">Loading pawn gold...</td></tr></tbody></table></div></div>
<div class="page-card mb-3"><div class="page-head compact-head"><div class="section-title">Pledge Summary</div></div><div class="card-body-x compact-body"><div class="summary-grid"><div class="summary-box"><span>Selected Items</span><strong id="sumItems">0</strong></div><div class="summary-box"><span>Pawn Customers</span><strong id="sumPawns">0</strong></div><div class="summary-box"><span>Total Net Weight</span><strong><span id="sumNet">0.000</span> g</strong></div><div class="summary-box"><span>Allocated Principal</span><strong>₹<span id="sumAllocated">0.00</span></strong></div></div><div class="mt-3 d-flex justify-content-end"><button type="submit" id="saveBtn" class="btn-theme"><i class="fa-solid fa-check me-1"></i><span id="saveText"><?= $loanId?'Update Bank Pawn':'Create Bank Pawn' ?></span></button></div></div></div>
</form>
<?php include('includes/footer.php'); ?></div></main><?php include('includes/script.php'); ?><script src="assets/js/script.js"></script>
<script>
(function(){'use strict';const api='api/pawn-bank.php',csrf=<?= json_encode($csrfToken) ?>,editId=<?= (int)$loanId ?>,$=id=>document.getElementById(id);let data={banks:[],items:[],loan:null,financial_locked:false};
function money(v){return Number(v||0).toLocaleString('en-IN',{minimumFractionDigits:2,maximumFractionDigits:2})}function esc(v){return String(v==null?'':v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]))}function toast(ok,msg){const x=document.createElement('div');x.className='toast-x '+(ok?'ok':'bad');x.textContent=msg;document.body.appendChild(x);setTimeout(()=>x.remove(),3500)}async function req(o){const f=new FormData();Object.keys(o).forEach(k=>f.append(k,o[k]));f.append('csrf_token',csrf);const r=await fetch(api,{method:'POST',body:f,credentials:'same-origin',headers:{Accept:'application/json'}}),raw=await r.text();let j;try{j=JSON.parse(raw)}catch(e){throw new Error(raw.replace(/<[^>]*>/g,' ').trim().slice(0,300)||'Invalid server response')}if(!r.ok||!j.success)throw new Error(j.message||'Request failed');return j}
function renderItems(){const q=$('searchItems').value.trim().toLowerCase(),rows=data.items.filter(x=>!q||[x.pawn_no,x.customer_name,x.mobile,x.item_description,x.metal_name].join(' ').toLowerCase().includes(q));$('itemBody').innerHTML=rows.length?rows.map(x=>`<tr data-id="${x.id}"><td><input class="item-check" type="checkbox" value="${x.id}" ${x.selected?'checked':''} ${data.financial_locked?'disabled':''}></td><td><strong>${esc(x.pawn_no)} · ${esc(x.customer_name)}</strong><div class="mini-note">${esc(x.mobile||'')} · ${esc(x.pawn_date||'')}</div></td><td>${esc(x.item_description||'Pawn item')}</td><td>${esc(x.metal_name||'')}</td><td>${Number(x.quantity||0).toFixed(3)}</td><td>${Number(x.gross_weight||0).toFixed(3)}</td><td>${Number(x.stone_weight||0).toFixed(3)}</td><td><strong>${Number(x.net_weight||0).toFixed(3)}</strong></td><td>₹${money(x.estimated_value)}</td><td><input type="number" min="0" step="0.01" class="form-control form-control-sm allocation" value="${Number(x.allocated_bank_principal||0).toFixed(2)}" ${(!x.selected||data.financial_locked)?'disabled':''}></td></tr>`).join(''):'<tr><td colspan="10" class="text-center text-muted p-4">No eligible pawn gold found.</td></tr>';bindRows();updateSummary()}
function bindRows(){document.querySelectorAll('.item-check').forEach(c=>c.onchange=()=>{const a=c.closest('tr').querySelector('.allocation');a.disabled=!c.checked||data.financial_locked;if(!c.checked)a.value='0';updateSummary()});document.querySelectorAll('.allocation').forEach(a=>a.oninput=updateSummary)}function selectedRows(){return Array.from(document.querySelectorAll('#itemBody tr')).filter(r=>r.querySelector('.item-check')&&r.querySelector('.item-check').checked)}function updateSummary(){const rows=selectedRows(),ids=rows.map(r=>Number(r.dataset.id)),items=data.items.filter(x=>ids.includes(Number(x.id))),pawns=new Set(items.map(x=>x.pawn_entry_id)),net=items.reduce((s,x)=>s+Number(x.net_weight||0),0),allocated=rows.reduce((s,r)=>s+Number(r.querySelector('.allocation').value||0),0);$('sumItems').textContent=items.length;$('sumPawns').textContent=pawns.size;$('sumNet').textContent=net.toFixed(3);$('sumAllocated').textContent=money(allocated)}
function fillLoan(l){if(!l)return;$('bankId').value=l.bank_id;$('bankLoanNo').value=l.bank_loan_no;$('pledgeDate').value=l.pledge_date;$('bankPrincipal').value=Number(l.principal_amount||0).toFixed(2);$('bankRate').value=Number(l.bank_interest_percent||0).toFixed(3);$('bankPeriod').value=l.bank_interest_period;$('bankMethod').value=l.bank_interest_method;$('payCycle').value=l.interest_payment_cycle;$('cycleMonths').value=l.interest_cycle_months||12;$('maturityDate').value=l.maturity_date||'';$('bankDocumentNo').value=l.bank_document_no||'';$('remarks').value=l.remarks||'';cycleUi()}
function cycleUi(){$('customMonthsWrap').classList.toggle('d-none',$('payCycle').value!=='Custom');const map={Monthly:1,Quarterly:3,'Half-Yearly':6,Yearly:12};if(!editId&&map[$('payCycle').value])$('cycleMonths').value=map[$('payCycle').value]}
async function init(){try{const j=await req({action:'entry_init',loan_id:editId});data=j;$('bankId').innerHTML='<option value="">Select bank</option>'+data.banks.map(b=>`<option value="${b.id}">${esc(b.bank_name)}${b.branch_name?' · '+esc(b.branch_name):''}</option>`).join('');fillLoan(data.loan);if(data.financial_locked){$('lockNote').classList.remove('d-none');$('lockNote').textContent='Financial editing is locked because this bank pawn already has posted payment/interest activity. You can still edit maturity date, bank document number and remarks.';document.querySelectorAll('.financial').forEach(x=>x.disabled=true)}renderItems()}catch(e){toast(false,e.message)}}
$('searchItems').oninput=renderItems;$('selectAllBtn').onclick=()=>{if(data.financial_locked)return;const cs=Array.from(document.querySelectorAll('.item-check'));const all=cs.length&&cs.every(c=>c.checked);cs.forEach(c=>{c.checked=!all;const a=c.closest('tr').querySelector('.allocation');a.disabled=all;if(all)a.value='0'});updateSummary()};$('payCycle').onchange=cycleUi;
$('bankForm').onsubmit=async e=>{e.preventDefault();const rows=selectedRows();if(!data.financial_locked&&!rows.length)return toast(false,'Select at least one pawn gold item.');const allocations={},ids=[];rows.forEach(r=>{const id=Number(r.dataset.id);ids.push(id);allocations[id]=Number(r.querySelector('.allocation').value||0)});if(!data.financial_locked){const principal=Number($('bankPrincipal').value||0),allocated=Object.values(allocations).reduce((s,v)=>s+v,0);if(allocated>principal+0.009)return toast(false,'Allocated item principal cannot exceed bank principal received.')}const f=new FormData(e.target);f.append('action','save');f.append('csrf_token',csrf);f.append('item_ids',JSON.stringify(ids));f.append('allocations',JSON.stringify(allocations));document.querySelectorAll('.financial:disabled').forEach(x=>{if(x.name)f.append(x.name,x.value)});const b=$('saveBtn');b.disabled=true;try{const r=await fetch(api,{method:'POST',body:f,credentials:'same-origin',headers:{Accept:'application/json'}}),raw=await r.text();let j;try{j=JSON.parse(raw)}catch(x){throw new Error(raw.replace(/<[^>]*>/g,' ').trim().slice(0,300))}if(!r.ok||!j.success)throw new Error(j.message||'Unable to save bank pawn');toast(true,j.message);setTimeout(()=>location.href='pawn-bank.php',700)}catch(x){toast(false,x.message)}finally{b.disabled=false}};init()})();
</script></body></html>
