<?php require __DIR__.'/_common.php';$pawnId=(int)($_GET['id']??0);if($pawnId<=0){header('Location: pawn-list.php');exit;} ?>
<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title><?=e($businessName)?> - Pawn View</title><?php include('includes/links.php');require __DIR__.'/_style.php';?></head><body>
<?php include('includes/sidebar.php');?><main class="app-main"><?php include('includes/nav.php');?><div class="content-wrap">
<div class="page-card mb-3"><div class="page-head"><div><div class="page-title">Pawn Details</div><div class="small text-muted" id="pawnSub">Loading...</div></div><div class="d-flex gap-2"><a href="pawn-list.php" class="btn-soft">Back</a><a href="pawn-payment.php?pawn_id=<?=$pawnId?>" class="btn-theme">Make Payment</a></div></div></div>
<div id="loading" class="page-card loading show">Loading pawn details...</div><div id="content" style="display:none">
<div class="stat-grid mb-3"><div class="stat-card"><div class="stat-label">Principal</div><div class="stat-value" id="vPrincipal"></div></div><div class="stat-card"><div class="stat-label">Balance</div><div class="stat-value" id="vBalance"></div></div><div class="stat-card"><div class="stat-label">Principal Paid</div><div class="stat-value" id="vPaid"></div></div><div class="stat-card"><div class="stat-label">Interest Collected</div><div class="stat-value" id="vInterest"></div></div></div>
<div class="row g-3 mb-3"><div class="col-lg-6"><div class="page-card h-100"><div class="page-head"><div class="section-title">Loan Information</div></div><div class="card-body-x" id="loanInfo"></div></div></div><div class="col-lg-6"><div class="page-card h-100"><div class="page-head"><div class="section-title">Customer Information</div></div><div class="card-body-x" id="customerInfo"></div></div></div></div>
<div class="page-card mb-3"><div class="page-head"><div class="section-title">Pawn Items</div></div><div class="table-responsive"><table class="table mb-0"><thead><tr><th>Item</th><th>Metal</th><th>Qty</th><th>Gross</th><th>Stone</th><th>Net</th><th>Purity</th><th class="text-end">Estimated Value</th></tr></thead><tbody id="itemsBody"></tbody></table></div></div>
<div class="row g-3"><div class="col-lg-6"><div class="page-card"><div class="page-head"><div class="section-title">Payment History</div></div><div class="table-responsive"><table class="table mb-0"><thead><tr><th>Date</th><th>Receipt</th><th>Principal</th><th>Interest</th><th>Total</th></tr></thead><tbody id="paymentsBody"></tbody></table></div></div></div><div class="col-lg-6"><div class="page-card"><div class="page-head"><div class="section-title">Interest Collections</div></div><div class="table-responsive"><table class="table mb-0"><thead><tr><th>Date</th><th>Receipt</th><th>Interest</th><th>Penalty</th><th>Total</th></tr></thead><tbody id="interestBody"></tbody></table></div></div></div></div></div>
<?php include('includes/footer.php');?></div></main><?php include('includes/script.php');?><script src="assets/js/script.js"></script>
<script>
(()=>{'use strict';const api='api/pawn.php',csrf=<?=json_encode($csrfToken)?>,id=<?=$pawnId?>;function esc(v){return String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#039;','"':'&quot;'}[c]))}function money(v){return Number(v||0).toLocaleString('en-IN',{minimumFractionDigits:2,maximumFractionDigits:2})}async function load(){const f=new FormData();f.append('action','view');f.append('pawn_id',id);f.append('csrf_token',csrf);const r=await fetch(api,{method:'POST',body:f,credentials:'same-origin',headers:{Accept:'application/json'}}),raw=await r.text();let d;try{d=JSON.parse(raw)}catch(e){return alert(raw.slice(0,220))}if(!r.ok||!d.success)return alert(d.message||'Unable to load');const p=d.pawn;pawnSub.textContent=p.pawn_no+' - '+p.customer_name;vPrincipal.textContent='₹'+money(p.principal_amount);vBalance.textContent='₹'+money(p.balance_principal);vPaid.textContent='₹'+money(p.total_principal_paid);vInterest.textContent='₹'+money(p.total_interest_collected);loanInfo.innerHTML=`Pawn No: <b>${esc(p.pawn_no)}</b><hr>Date: ${esc(p.pawn_date_display)}<hr>Category: ${esc(p.category_name)}<hr>Interest: ${Number(p.interest_percent).toFixed(3)}% ${esc(p.interest_period)}<hr>Due Date: ${esc(p.due_date_display||'-')}<hr>Status: ${esc(p.status)}<hr>Gross / Net: ${Number(p.total_gross_weight).toFixed(3)} / ${Number(p.total_net_weight).toFixed(3)} g`;customerInfo.innerHTML=`Name: <b>${esc(p.customer_name)}</b><hr>Mobile: ${esc(p.mobile||'')}<hr>Code: ${esc(p.customer_code||'')}<hr>Address: ${esc([p.address_line1,p.address_line2,p.city,p.state,p.pincode].filter(Boolean).join(', '))}<hr>Remarks: ${esc(p.remarks||'')}`;itemsBody.innerHTML=d.items.map(x=>`<tr><td>${esc(x.item_description)}</td><td>${esc(x.metal_name)}</td><td>${Number(x.quantity).toFixed(3)}</td><td>${Number(x.gross_weight).toFixed(3)}</td><td>${Number(x.stone_weight).toFixed(3)}</td><td>${Number(x.net_weight).toFixed(3)}</td><td>${x.purity??''}</td><td class="text-end">₹${money(x.estimated_value)}</td></tr>`).join('');paymentsBody.innerHTML=d.payments.length?d.payments.map(x=>`<tr><td>${esc(x.payment_date_display)}</td><td>${esc(x.receipt_no)}</td><td>₹${money(x.principal_amount)}</td><td>₹${money(x.interest_amount)}</td><td>₹${money(x.total_amount)}</td></tr>`).join(''):'<tr><td colspan="5" class="text-center">No payments</td></tr>';interestBody.innerHTML=d.interests.length?d.interests.map(x=>`<tr><td>${esc(x.collection_date_display)}</td><td>${esc(x.receipt_no)}</td><td>₹${money(x.interest_amount)}</td><td>₹${money(x.penalty_amount)}</td><td>₹${money(x.total_amount)}</td></tr>`).join(''):'<tr><td colspan="5" class="text-center">No interest collections</td></tr>';loading.classList.remove('show');content.style.display=''}load()})();
</script></body></html>
