<?php
if (session_status() === PHP_SESSION_NONE) session_start();
date_default_timezone_set((string)($_SESSION['timezone'] ?? 'Asia/Kolkata'));
foreach ([__DIR__.'/config/config.php',__DIR__.'/config.php',__DIR__.'/includes/config.php',__DIR__.'/super-admin/includes/config.php'] as $f) {
    if (is_file($f)) { require_once $f; break; }
}
if (!isset($conn) || !($conn instanceof mysqli)) die('Database configuration is not available.');
$conn->set_charset('utf8mb4');
if (empty($_SESSION['user_id'])) { header('Location: login.php'); exit; }
function e($v): string { return htmlspecialchars((string)($v ?? ''), ENT_QUOTES, 'UTF-8'); }
$businessId=(int)($_SESSION['business_id']??0);
$branchId=(int)($_SESSION['branch_id']??($_SESSION['default_branch_id']??0));
if($businessId<=0||$branchId<=0) die('A valid business and branch must be selected.');
if(empty($_SESSION['pawn_customer_csrf'])) $_SESSION['pawn_customer_csrf']=bin2hex(random_bytes(32));
$csrfToken=(string)$_SESSION['pawn_customer_csrf'];
$theme=['primary_color'=>'#d89416','primary_dark_color'=>'#b86a0b','primary_soft_color'=>'#fff6e5','page_background'=>'#f4f3f0','card_background'=>'#fff','text_color'=>'#171717','muted_text_color'=>'#7d8794','border_color'=>'#e8e8e8','font_family'=>'Inter','heading_font_family'=>'Playfair Display','border_radius_px'=>12,'sidebar_width_px'=>230,'sidebar_gradient_1'=>'#171c21','sidebar_gradient_2'=>'#20272d','sidebar_gradient_3'=>'#101419'];
$stmt=$conn->prepare('SELECT * FROM business_theme_settings WHERE business_id=? LIMIT 1');
if($stmt){$stmt->bind_param('i',$businessId);$stmt->execute();$r=$stmt->get_result()->fetch_assoc()?:[];$stmt->close();foreach($theme as $k=>$v)if(isset($r[$k])&&$r[$k]!=='')$theme[$k]=$r[$k];}
$businessName=(string)($_SESSION['business_name']??'Jewellery ERP');
?>
<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title><?=e($businessName)?> - Pawn Customers</title><?php include('includes/links.php'); ?><style>
:root{--primary:<?=e($theme['primary_color'])?>;--primary-dark:<?=e($theme['primary_dark_color'])?>;--primary-soft:<?=e($theme['primary_soft_color'])?>;--page-bg:<?=e($theme['page_background'])?>;--card-bg:<?=e($theme['card_background'])?>;--text:<?=e($theme['text_color'])?>;--muted:<?=e($theme['muted_text_color'])?>;--line:<?=e($theme['border_color'])?>;--radius:<?=(int)$theme['border_radius_px']?>px;--sidebar-width:<?=(int)$theme['sidebar_width_px']?>px;--sidebar-gradient-1:<?=e($theme['sidebar_gradient_1'])?>;--sidebar-gradient-2:<?=e($theme['sidebar_gradient_2'])?>;--sidebar-gradient-3:<?=e($theme['sidebar_gradient_3'])?>}
body{background:var(--page-bg);color:var(--text);font-family:<?=json_encode($theme['font_family'])?>,sans-serif}.sidebar{background:linear-gradient(180deg,var(--sidebar-gradient-1),var(--sidebar-gradient-2),var(--sidebar-gradient-3))!important}.page-card,.stat-card{background:var(--card-bg);border:1px solid var(--line);border-radius:var(--radius)}.page-head{padding:15px 17px;border-bottom:1px solid var(--line);display:flex;justify-content:space-between;align-items:center;gap:12px}.page-title{font:700 20px <?=json_encode($theme['heading_font_family'])?>,serif}.section-title{font-size:10px;font-weight:800;text-transform:uppercase;color:var(--primary-dark)}.card-body-x{padding:15px}.form-control,.form-select{min-height:39px;border:1px solid var(--line);border-radius:9px;background:var(--card-bg);color:var(--text);font-size:11px}.btn-theme{border:0;border-radius:9px;padding:9px 15px;color:#fff;background:linear-gradient(135deg,var(--primary),var(--primary-dark));font-size:11px;font-weight:700;text-decoration:none}.btn-soft{border:1px solid var(--line);border-radius:9px;padding:9px 15px;background:var(--card-bg);color:var(--text);font-size:11px;text-decoration:none}.stat-grid{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:10px}.stat-card{padding:14px}.stat-label{font-size:10px;color:var(--muted)}.stat-value{font-size:20px;font-weight:800}.table{font-size:10px}.table th{font-size:9px;text-transform:uppercase;color:var(--muted);background:color-mix(in srgb,var(--muted) 6%,transparent);white-space:nowrap}.table td,.table th{border-color:var(--line);vertical-align:middle}.badge-soft{padding:4px 8px;border-radius:999px;font-size:9px;font-weight:700}.risk-low{background:#eaf8f0;color:#168449}.risk-medium{background:#fff4d8;color:#9a6700}.risk-high{background:#fdecec;color:#bd2d2d}.kyc-ok{background:#eaf2ff;color:#2457a7}.kyc-pending{background:#edf0f2;color:#5f6b74}.loading,.empty{display:none;padding:40px;text-align:center;color:var(--muted)}.loading.show,.empty.show{display:block}.theme-toast{position:fixed;right:18px;top:78px;z-index:20000;padding:11px 14px;border-radius:10px;color:#fff;font-size:11px;font-weight:600;opacity:0;transform:translateY(-10px);transition:.22s}.theme-toast.show{opacity:1;transform:none}.theme-toast-success{background:#168449}.theme-toast-error{background:#c0392b}.preview{width:92px;height:92px;object-fit:cover;border-radius:10px;border:1px solid var(--line)}.doc-link{font-size:10px}.info-row{display:flex;gap:12px;padding:8px 0;border-bottom:1px dashed var(--line)}.info-label{width:145px;color:var(--muted);font-size:10px}.info-value{font-size:11px;font-weight:600;flex:1}body.dark-mode,body[data-theme=dark]{--page-bg:#0f151b;--card-bg:#182129;--text:#f3f6f8;--muted:#9aa7b3;--line:#2c3944}@media(max-width:991px){.stat-grid{grid-template-columns:1fr 1fr}}@media(max-width:767px){.stat-grid{grid-template-columns:1fr}}
</style></head><body>
<?php include('includes/sidebar.php'); ?><main class="app-main"><?php include('includes/nav.php'); ?><div class="content-wrap">
<div class="page-card mb-3"><div class="page-head"><div><div class="page-title">Pawn Customers</div><div class="small text-muted">Manage KYC, risk and loan profiles.</div></div><a href="pawn-customer-add.php" class="btn-theme">Add Pawn Customer</a></div></div>
<div class="stat-grid mb-3"><div class="stat-card"><div class="stat-label">Total Customers</div><div class="stat-value" id="sTotal">0</div></div><div class="stat-card"><div class="stat-label">Credit Limit</div><div class="stat-value" id="sCredit">₹0.00</div></div><div class="stat-card"><div class="stat-label">KYC Verified</div><div class="stat-value" id="sKyc">0</div></div><div class="stat-card"><div class="stat-label">Active Loans</div><div class="stat-value" id="sLoans">0</div></div></div>
<div class="page-card mb-3"><div class="card-body-x"><form id="filterForm" class="row g-2"><div class="col-md-4"><input id="search" class="form-control" placeholder="Name, code, mobile or email"></div><div class="col-md-2"><select id="risk" class="form-select"><option value="">All Risk</option><option>Low</option><option>Medium</option><option>High</option></select></div><div class="col-md-2"><select id="kyc" class="form-select"><option value="">All KYC</option><option value="1">Verified</option><option value="0">Pending</option></select></div><div class="col-md-2"><select id="occupation" class="form-select"><option value="">All Occupations</option></select></div><div class="col-md-2 d-flex gap-2"><button class="btn-theme flex-grow-1">Search</button><button type="button" id="reset" class="btn-soft">Reset</button></div></form></div></div>
<div class="page-card"><div class="loading" id="loading">Loading customers...</div><div class="table-responsive" id="tableWrap"><table class="table mb-0"><thead><tr><th>Customer</th><th>Contact</th><th>Occupation</th><th class="text-end">Credit Limit</th><th>Risk</th><th>KYC</th><th>Active Loans</th><th>Actions</th></tr></thead><tbody id="tbody"></tbody></table></div><div class="empty" id="empty">No pawn customers found.</div><div class="p-3 d-flex justify-content-between"><span class="small text-muted" id="summary"></span><div id="pages"></div></div></div>
<?php include('includes/footer.php'); ?></div></main><?php include('includes/script.php'); ?><script src="assets/js/script.js"></script>
<script>
(()=>{'use strict';const api='api/pawn-customers.php',csrf=<?=json_encode($csrfToken)?>;const els={loading:document.getElementById('loading'),table:document.getElementById('tableWrap'),empty:document.getElementById('empty'),body:document.getElementById('tbody'),search:document.getElementById('search'),risk:document.getElementById('risk'),kyc:document.getElementById('kyc'),occupation:document.getElementById('occupation'),summary:document.getElementById('summary'),pages:document.getElementById('pages')};
function esc(v){return String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#039;','"':'&quot;'}[c]))}function money(v){return Number(v||0).toLocaleString('en-IN',{minimumFractionDigits:2,maximumFractionDigits:2})}async function req(d){const f=new FormData();Object.entries(d).forEach(([k,v])=>f.append(k,v));f.append('csrf_token',csrf);const r=await fetch(api,{method:'POST',body:f,credentials:'same-origin',headers:{Accept:'application/json'}}),raw=await r.text();let j;try{j=JSON.parse(raw)}catch(e){throw new Error(raw.slice(0,250))}if(!r.ok||!j.success)throw new Error(j.message||'Request failed');return j}
function badge(risk){return `<span class="badge-soft risk-${String(risk).toLowerCase()}">${esc(risk)}</span>`}
async function load(p=1){els.loading.classList.add('show');try{const d=await req({action:'list',page:p,per_page:15,search:els.search.value.trim(),risk:els.risk.value,kyc:els.kyc.value,occupation:els.occupation.value});els.body.innerHTML=d.customers.map(c=>`<tr><td><strong>${esc(c.customer_name)}</strong><div class="small text-muted">${esc(c.customer_code)}</div></td><td>${esc(c.mobile||'')}<div class="small text-muted">${esc(c.email||'')}</div></td><td>${esc(c.occupation||'-')}</td><td class="text-end">₹${money(c.credit_limit)}</td><td>${badge(c.risk_category)}</td><td><span class="badge-soft ${Number(c.kyc_verified)===1?'kyc-ok':'kyc-pending'}">${Number(c.kyc_verified)===1?'Verified':'Pending'}</span></td><td>${c.active_loans}</td><td><a class="btn-soft py-1 px-2" href="pawn-customer-view.php?id=${c.id}">View</a> <a class="btn-soft py-1 px-2" href="pawn-customer-add.php?id=${c.id}">Edit</a></td></tr>`).join('');els.empty.classList.toggle('show',!d.customers.length);els.table.style.display=d.customers.length?'':'none';sTotal.textContent=d.stats.total_customers;sCredit.textContent='₹'+money(d.stats.total_credit_limit);sKyc.textContent=d.stats.kyc_verified_count;sLoans.textContent=d.stats.active_loans;els.summary.textContent=`Showing ${d.meta.from}-${d.meta.to} of ${d.meta.total}`;els.pages.innerHTML=Array.from({length:d.meta.total_pages},(_,i)=>`<button type="button" class="btn-soft py-1 px-2 ms-1 pg" data-p="${i+1}">${i+1}</button>`).join('');if(!els.occupation.dataset.loaded){els.occupation.innerHTML='<option value="">All Occupations</option>'+d.occupations.map(o=>`<option>${esc(o)}</option>`).join('');els.occupation.dataset.loaded='1'}}catch(e){alert(e.message)}finally{els.loading.classList.remove('show')}}filterForm.onsubmit=e=>{e.preventDefault();load(1)};reset.onclick=()=>{els.search.value='';els.risk.value='';els.kyc.value='';els.occupation.value='';load(1)};document.addEventListener('click',e=>{const b=e.target.closest('.pg');if(b)load(Number(b.dataset.p))});load(1)})();
</script></body></html>