<?php
if (session_status() === PHP_SESSION_NONE) session_start();
date_default_timezone_set((string)($_SESSION['timezone'] ?? 'Asia/Kolkata'));
mysqli_report(MYSQLI_REPORT_OFF);
foreach ([__DIR__.'/config/config.php',__DIR__.'/config.php',__DIR__.'/includes/config.php',__DIR__.'/super-admin/includes/config.php'] as $f) { if (is_file($f)) { require_once $f; break; } }
if (!isset($conn) || !($conn instanceof mysqli)) die('Database configuration is not available.');
$conn->set_charset('utf8mb4');
if (empty($_SESSION['user_id'])) die('Session expired.');
function sxTableExists(mysqli $conn,$table){$safe=$conn->real_escape_string((string)$table);$r=$conn->query("SHOW TABLES LIKE '{$safe}'");return $r&&$r->num_rows>0;}
function sxBind(mysqli_stmt $stmt,$types,array &$params){if($types==='')return;$a=[$types];foreach($params as $k=>$v)$a[]=&$params[$k];call_user_func_array([$stmt,'bind_param'],$a);}
function sxValidDate($value){$d=DateTime::createFromFormat('Y-m-d',(string)$value);return $d&&$d->format('Y-m-d')===$value;}
function sx($v){return htmlspecialchars((string)($v??''),ENT_QUOTES,'UTF-8');}
function sxMoney($v){return number_format((float)$v,2,'.','');}
$businessId=(int)($_SESSION['business_id']??0);$branchId=(int)($_SESSION['branch_id']??($_SESSION['default_branch_id']??0));if($businessId<=0)die('A valid business must be selected.');
$fromDate=trim((string)($_GET['from_date']??date('Y-m-01')));$toDate=trim((string)($_GET['to_date']??date('Y-m-d')));$customerId=(int)($_GET['customer_id']??0);$billType=trim((string)($_GET['bill_type']??''));$paymentStatus=trim((string)($_GET['payment_status']??''));$search=trim((string)($_GET['search']??''));
if(!sxValidDate($fromDate))$fromDate=date('Y-m-01');if(!sxValidDate($toDate))$toDate=date('Y-m-d');if($fromDate>$toDate){$t=$fromDate;$fromDate=$toDate;$toDate=$t;}
$where=" WHERE s.business_id=? AND COALESCE(s.workflow_status,'Posted') <> 'Cancelled'";$types='i';$params=[$businessId];if($branchId>0){$where.=' AND s.branch_id=?';$types.='i';$params[]=$branchId;}$where.=' AND s.invoice_date>=? AND s.invoice_date<=?';$types.='ss';$params[]=$fromDate;$params[]=$toDate;if($customerId>0){$where.=' AND s.customer_id=?';$types.='i';$params[]=$customerId;}if($billType!==''){$where.=' AND s.bill_type=?';$types.='s';$params[]=$billType;}if(in_array($paymentStatus,['Unpaid','Partial','Paid'],true)){$where.=' AND s.payment_status=?';$types.='s';$params[]=$paymentStatus;}if($search!==''){$like='%'.$search.'%';$where.=" AND (s.invoice_no LIKE ? OR COALESCE(s.customer_name,'') LIKE ? OR COALESCE(s.customer_mobile,'') LIKE ?)";$types.='sss';$params[]=$like;$params[]=$like;$params[]=$like;}
$methodSelect="'' AS method_name";if(sxTableExists($conn,'sale_payments')&&sxTableExists($conn,'payment_methods')){$methodSelect="COALESCE((SELECT GROUP_CONCAT(DISTINCT pm.method_name ORDER BY sp.id SEPARATOR ', ') FROM sale_payments sp INNER JOIN payment_methods pm ON pm.id=sp.payment_method_id AND pm.business_id=sp.business_id WHERE sp.sale_id=s.id AND sp.business_id=s.business_id),'') AS method_name";}
$sql="SELECT s.invoice_no AS bill_no,s.invoice_date AS bill_date,s.invoice_time AS bill_time,s.customer_name,s.customer_mobile,s.bill_type,{$methodSelect},s.subtotal,s.discount_amount,s.taxable_amount,s.cgst_amount,s.sgst_amount,s.igst_amount,s.round_off,s.grand_total,s.paid_amount,s.balance_amount,s.payment_status FROM sales s {$where} ORDER BY s.invoice_date DESC,s.invoice_time DESC,s.id DESC";$stmt=$conn->prepare($sql);if(!$stmt)die('Unable to prepare sales report: '.$conn->error);$p=$params;sxBind($stmt,$types,$p);$stmt->execute();$r=$stmt->get_result();$rows=[];while($x=$r->fetch_assoc())$rows[]=$x;$stmt->close();
$filename='sales-report-'.date('Ymd-His').'.xls';header('Content-Type: application/vnd.ms-excel; charset=UTF-8');header('Content-Disposition: attachment; filename="'.$filename.'"');header('Cache-Control: max-age=0');echo "\xEF\xBB\xBF";
$businessName=(string)($_SESSION['business_name']??'Sales Report');$branchName=(string)($_SESSION['branch_name']??'');
?><html><head><meta charset="UTF-8"><style>body{font-family:Arial,sans-serif}table{border-collapse:collapse}th,td{border:1px solid #c9b48b;padding:5px 7px;font-size:10px;white-space:nowrap}th{background:#7b1f3a;color:#fff}.title{font-size:16px;font-weight:bold;text-align:center}.sub{text-align:center;font-size:10px}.num{text-align:right}.sum{background:#f8ecd0;font-weight:bold}</style></head><body>
<table><tr><td colspan="18" class="title"><?php echo sx($businessName); ?></td></tr><?php if($branchName!==''): ?><tr><td colspan="18" class="sub"><?php echo sx($branchName); ?></td></tr><?php endif; ?><tr><td colspan="18" class="sub">Sales Report | Period: <?php echo sx(date('d-m-Y',strtotime($fromDate))); ?> to <?php echo sx(date('d-m-Y',strtotime($toDate))); ?></td></tr><tr><th>S.No</th><th>Bill No</th><th>Date</th><th>Time</th><th>Customer</th><th>Mobile</th><th>Bill Type</th><th>Method</th><th>Subtotal</th><th>Discount</th><th>Taxable</th><th>CGST</th><th>SGST</th><th>IGST</th><th>Round Off</th><th>Grand Total</th><th>Paid</th><th>Balance / Status</th></tr>
<?php $tot=['subtotal'=>0,'discount_amount'=>0,'taxable_amount'=>0,'cgst_amount'=>0,'sgst_amount'=>0,'igst_amount'=>0,'round_off'=>0,'grand_total'=>0,'paid_amount'=>0,'balance_amount'=>0]; foreach($rows as $i=>$row): foreach($tot as $k=>$v)$tot[$k]+=(float)($row[$k]??0); ?>
<tr><td><?php echo $i+1; ?></td><td><?php echo sx($row['bill_no']); ?></td><td><?php echo sx(date('d-m-Y',strtotime($row['bill_date']))); ?></td><td><?php echo sx(!empty($row['bill_time'])?date('h:i A',strtotime($row['bill_time'])):''); ?></td><td><?php echo sx($row['customer_name']?:'Walk-in Customer'); ?></td><td><?php echo sx($row['customer_mobile']); ?></td><td><?php echo sx($row['bill_type']); ?></td><td><?php echo sx($row['method_name']); ?></td><td class="num"><?php echo sxMoney($row['subtotal']); ?></td><td class="num"><?php echo sxMoney($row['discount_amount']); ?></td><td class="num"><?php echo sxMoney($row['taxable_amount']); ?></td><td class="num"><?php echo sxMoney($row['cgst_amount']); ?></td><td class="num"><?php echo sxMoney($row['sgst_amount']); ?></td><td class="num"><?php echo sxMoney($row['igst_amount']); ?></td><td class="num"><?php echo sxMoney($row['round_off']); ?></td><td class="num"><?php echo sxMoney($row['grand_total']); ?></td><td class="num"><?php echo sxMoney($row['paid_amount']); ?></td><td><?php echo sx(sxMoney($row['balance_amount']).' / '.($row['payment_status']??'')); ?></td></tr>
<?php endforeach; ?>
<tr class="sum"><td colspan="8">Totals (<?php echo count($rows); ?> bills)</td><td class="num"><?php echo sxMoney($tot['subtotal']); ?></td><td class="num"><?php echo sxMoney($tot['discount_amount']); ?></td><td class="num"><?php echo sxMoney($tot['taxable_amount']); ?></td><td class="num"><?php echo sxMoney($tot['cgst_amount']); ?></td><td class="num"><?php echo sxMoney($tot['sgst_amount']); ?></td><td class="num"><?php echo sxMoney($tot['igst_amount']); ?></td><td class="num"><?php echo sxMoney($tot['round_off']); ?></td><td class="num"><?php echo sxMoney($tot['grand_total']); ?></td><td class="num"><?php echo sxMoney($tot['paid_amount']); ?></td><td class="num"><?php echo sxMoney($tot['balance_amount']); ?></td></tr></table></body></html>
