<?php
if(session_status()===PHP_SESSION_NONE)session_start();
ini_set('display_errors','0');
ini_set('html_errors','0');
error_reporting(E_ALL);
header('Content-Type: application/json; charset=utf-8');
ob_start();
register_shutdown_function(function():void{
    $error=error_get_last();
    if($error && in_array($error['type'],[E_ERROR,E_PARSE,E_CORE_ERROR,E_COMPILE_ERROR],true)){
        while(ob_get_level()>0){ob_end_clean();}
        http_response_code(500);
        echo json_encode(['success'=>false,'message'=>'PHP fatal error: '.$error['message'].' in '.basename($error['file']).' on line '.$error['line']],JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES);
    }
});
function respond(bool $success,string $message,array $extra=[],int $status=200):void{while(ob_get_level()>0){ob_end_clean();}http_response_code($status);header('Content-Type: application/json; charset=utf-8');echo json_encode(array_merge(['success'=>$success,'message'=>$message],$extra),JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES);exit;}
foreach([dirname(__DIR__).'/config/config.php',dirname(__DIR__).'/config.php',dirname(__DIR__).'/includes/config.php',dirname(__DIR__).'/super-admin/includes/config.php'] as $f){if(is_file($f)){require_once $f;break;}}
if(!isset($conn)||!($conn instanceof mysqli))respond(false,'Database configuration is not available.',[],500);$conn->set_charset('utf8mb4');
if(empty($_SESSION['user_id']))respond(false,'Your session has expired. Please log in again.',[],401);if($_SERVER['REQUEST_METHOD']!=='POST')respond(false,'Invalid request method.',[],405);if(!hash_equals((string)($_SESSION['billing_csrf']??''),(string)($_POST['csrf_token']??'')))respond(false,'Invalid or expired request token. Refresh the page and try again.',[],419);
function permission(mysqli $conn,string $action):bool{if(($_SESSION['user_type']??'')==='Platform Admin')return true;$map=['open'=>'can_open','create'=>'can_create'];$field=$map[$action]??'';foreach(['perm.billing.create','perm.billing'] as $c){if(isset($_SESSION['permissions'][$c][$field]))return(int)$_SESSION['permissions'][$c][$field]===1;}$b=(int)($_SESSION['business_id']??0);$r=(int)($_SESSION['role_id']??0);if(!$b||!$r)return false;$stmt=$conn->prepare("SELECT rp.`{$field}` FROM role_permissions rp JOIN permissions p ON p.id=rp.permission_id WHERE rp.business_id=? AND rp.role_id=? AND p.permission_code IN ('perm.billing.create','perm.billing') ORDER BY FIELD(p.permission_code,'perm.billing.create','perm.billing') LIMIT 1");if(!$stmt)return false;$stmt->bind_param('ii',$b,$r);$stmt->execute();$x=$stmt->get_result()->fetch_assoc();$stmt->close();return(int)($x[$field]??0)===1;}
function audit(mysqli $conn,int $b,int $br,int $u,int $id,string $no):void{$stmt=$conn->prepare("INSERT INTO audit_logs (business_id,branch_id,user_id,module_code,action_type,reference_table,reference_id,description,new_values_json,ip_address,user_agent) VALUES (?,?,?,'billing.sales','Create','sales',?,?,?, ?,?)");if(!$stmt)return;$desc='Created invoice '.$no;$json=json_encode(['invoice_no'=>$no],JSON_UNESCAPED_UNICODE);$ip=(string)($_SERVER['REMOTE_ADDR']??'');$ua=(string)($_SERVER['HTTP_USER_AGENT']??'');$stmt->bind_param('iiiissss',$b,$br,$u,$id,$desc,$json,$ip,$ua);$stmt->execute();$stmt->close();}
function invoiceNo(mysqli $conn,int $b,int $br):array{$stmt=$conn->prepare("SELECT * FROM invoice_settings WHERE business_id=? AND (branch_id=? OR branch_id IS NULL) AND document_type='Invoice' AND is_active=1 ORDER BY (branch_id=? ) DESC,is_default DESC,id DESC LIMIT 1");$s=null;if($stmt){$stmt->bind_param('iii',$b,$br,$br);$stmt->execute();$s=$stmt->get_result()->fetch_assoc();$stmt->close();}$id=(int)($s['id']??0);$digits=max(1,(int)($s['sequence_digits']??4));$start=max(1,(int)($s['sequence_start']??1));$stmt=$conn->prepare('SELECT COUNT(*) cnt FROM sales WHERE business_id=? AND branch_id=?');$stmt->bind_param('ii',$b,$br);$stmt->execute();$seq=$start+(int)($stmt->get_result()->fetch_assoc()['cnt']??0);$stmt->close();$fy=(int)date('n')>=4?date('y').'-'.date('y',strtotime('+1 year')):date('y',strtotime('-1 year')).'-'.date('y');$map=['{PREFIX}'=>$s['prefix']??'INV','{SPLITTER}'=>$s['splitter_symbol']??'','{FY_SHORT}'=>$fy,'{FY_2DIGIT}'=>str_replace('-','',$fy),'{YYYY}'=>date('Y'),'{MM}'=>date('m'),'{DD}'=>date('d'),'{SEQ}'=>str_pad((string)$seq,$digits,'0',STR_PAD_LEFT)];return[$id,strtr($s['format_template']??'{PREFIX}{YYYY}{MM}{DD}{SEQ}',$map)];}
if(($_POST['action']??'')!=='save')respond(false,'Invalid action.',[],400);if(!permission($conn,'create'))respond(false,'You do not have permission to create bills.',[],403);
$b=(int)($_SESSION['business_id']??0);$br=(int)($_SESSION['branch_id']??($_SESSION['default_branch_id']??0));$u=(int)$_SESSION['user_id'];if($b<=0||$br<=0)respond(false,'A valid business and branch must be selected.',[],403);
$date=trim((string)($_POST['invoice_date']??''));$time=trim((string)($_POST['invoice_time']??''));$type=(string)($_POST['bill_type']??'Retail');$customerRaw=(string)($_POST['customer_id']??'');$notes=trim((string)($_POST['notes']??''));if(!$date||!$time||!in_array($type,['Retail','GST','Estimate','Exchange'],true))respond(false,'Invalid bill details.');
$productIds=$_POST['product_id']??[];$quantities=$_POST['quantity']??[];$rates=$_POST['metal_rate']??[];$makings=$_POST['making_charge']??[];$stones=$_POST['stone_amount']??[];$others=$_POST['other_charge']??[];$discounts=$_POST['item_discount']??[];if(!is_array($productIds)||count($productIds)<1)respond(false,'Please add at least one product.');
$items=[];$subtotal=0;$itemDiscount=0;$taxable=0;$cgst=0;$sgst=0;
foreach($productIds as $i=>$pidRaw){$pid=(int)$pidRaw;$qty=(float)($quantities[$i]??0);if($pid<=0||$qty<=0)continue;$stmt=$conn->prepare("SELECT p.*,COALESCE(ps.quantity,0) stock_qty FROM products p LEFT JOIN product_stock ps ON ps.product_id=p.id AND ps.business_id=p.business_id AND ps.branch_id=? WHERE p.id=? AND p.business_id=? AND p.is_active=1 LIMIT 1");if(!$stmt)respond(false,'Unable to prepare product query: '.$conn->error,[],500);$stmt->bind_param('iii',$br,$pid,$b);$stmt->execute();$p=$stmt->get_result()->fetch_assoc();$stmt->close();if(!$p)respond(false,'Invalid product selected.');if((int)$p['track_stock']===1&&$qty>(float)$p['stock_qty'])respond(false,'Not enough stock for '.$p['product_name'].'.');$rate=(float)($rates[$i]??0);if($rate<=0)$rate=(float)$p['sale_rate'];$making=max(0,(float)($makings[$i]??0));$stone=max(0,(float)($stones[$i]??0));$other=max(0,(float)($others[$i]??0));$disc=max(0,(float)($discounts[$i]??0));$gross=(float)$p['gross_weight']*$qty;$stoneWeight=(float)$p['stone_weight']*$qty;$net=(float)$p['net_weight']*$qty;$metal=$net>0?$net*$rate:$qty*$rate;$waste=$metal*(float)$p['wastage_percent']/100;$rowSub=$metal+$making+$waste+$stone+$other;$rowTax=max(0,$rowSub-$disc);$tax=$rowTax*(float)$p['tax_percent']/100;$rowTotal=$rowTax+$tax;$items[]=['p'=>$p,'qty'=>$qty,'gross'=>$gross,'stone_weight'=>$stoneWeight,'net'=>$net,'rate'=>$rate,'waste'=>$waste,'making'=>$making,'stone'=>$stone,'other'=>$other,'disc'=>$disc,'tax'=>$tax,'total'=>$rowTotal,'cost'=>(float)$p['purchase_rate']*$qty];$subtotal+=$rowSub;$itemDiscount+=$disc;$taxable+=$rowTax;$cgst+=$tax/2;$sgst+=$tax/2;}
if(!$items)respond(false,'Please add valid products.');$overall=max(0,(float)($_POST['overall_discount']??0));$round=(float)($_POST['round_off']??0);$taxable=max(0,$taxable-$overall);$grand=$taxable+$cgst+$sgst+$round;$paid=max(0,min((float)($_POST['paid_amount']??0),$grand));$balance=$grand-$paid;$status=$paid<=0?'Unpaid':($balance>0.009?'Partial':'Paid');
$pmIds=$_POST['payment_method_id']??[];$pmAmounts=$_POST['payment_amount']??[];$pmRefs=$_POST['payment_reference']??[];$payRows=[];$split=0;foreach($pmIds as $i=>$idRaw){$id=(int)$idRaw;$amount=(float)($pmAmounts[$i]??0);$ref=trim((string)($pmRefs[$i]??''));if($id<=0&&$amount<=0&&$ref==='')continue;if($id<=0||$amount<=0)respond(false,'Complete all payment rows.');$stmt=$conn->prepare('SELECT id FROM payment_methods WHERE id=? AND business_id=? AND is_active=1');$stmt->bind_param('ii',$id,$b);$stmt->execute();$ok=$stmt->get_result()->fetch_assoc();$stmt->close();if(!$ok)respond(false,'Invalid payment method.');$payRows[]=[$id,$amount,$ref];$split+=$amount;}if($paid>0&&abs($split-$paid)>0.01)respond(false,'Split payment total must match Paid Amount.');if($paid<=0&&$payRows)respond(false,'Remove payment rows when Paid Amount is zero.');
$conn->begin_transaction();try{$customerId=0;$customerName='';$customerMobile='';if($customerRaw==='new'){$name=trim((string)($_POST['new_customer_name']??''));$mobile=trim((string)($_POST['new_customer_mobile']??''));$gstin=strtoupper(trim((string)($_POST['new_customer_gstin']??'')));if($name==='')throw new Exception('New customer name is required.');$stmt=$conn->prepare('SELECT COUNT(*) cnt FROM customers WHERE business_id=?');$stmt->bind_param('i',$b);$stmt->execute();$next=(int)$stmt->get_result()->fetch_assoc()['cnt']+1;$stmt->close();$code='CUS'.date('ymd').str_pad((string)$next,4,'0',STR_PAD_LEFT);$stmt=$conn->prepare("INSERT INTO customers (business_id,home_branch_id,customer_code,customer_type,customer_name,mobile,gstin,is_active) VALUES (?,?,?,'Billing',?,?,?,1)");if(!$stmt)throw new Exception('Customer insert prepare failed: '.$conn->error);$stmt->bind_param('iissss',$b,$br,$code,$name,$mobile,$gstin);if(!$stmt->execute())throw new Exception('Unable to create customer: '.$stmt->error);$customerId=(int)$stmt->insert_id;$stmt->close();$customerName=$name;$customerMobile=$mobile;}else{$customerId=(int)$customerRaw;if($customerId<=0)throw new Exception('Please select a customer.');$stmt=$conn->prepare("SELECT customer_name,mobile FROM customers WHERE id=? AND business_id=? AND is_active=1 LIMIT 1");$stmt->bind_param('ii',$customerId,$b);$stmt->execute();$c=$stmt->get_result()->fetch_assoc();$stmt->close();if(!$c)throw new Exception('Selected customer is invalid.');$customerName=$c['customer_name'];$customerMobile=$c['mobile']??'';}
[$settingId,$no]=invoiceNo($conn,$b,$br);$settingId=$settingId?:null;$stmt=$conn->prepare("INSERT INTO sales (business_id,branch_id,invoice_setting_id,invoice_no,invoice_date,invoice_time,customer_id,customer_name,customer_mobile,bill_type,subtotal,discount_amount,taxable_amount,cgst_amount,sgst_amount,igst_amount,round_off,grand_total,paid_amount,balance_amount,payment_status,workflow_status,notes,created_by) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,'Posted',?,?)");if(!$stmt)throw new Exception('Sales insert prepare failed: '.$conn->error);$igst=0.0;$discount=$itemDiscount+$overall;$stmt->bind_param('iiisssisssddddddddddssi',$b,$br,$settingId,$no,$date,$time,$customerId,$customerName,$customerMobile,$type,$subtotal,$discount,$taxable,$cgst,$sgst,$igst,$round,$grand,$paid,$balance,$status,$notes,$u);if(!$stmt->execute())throw new Exception('Unable to save sale: '.$stmt->error);$saleId=(int)$stmt->insert_id;$stmt->close();
foreach($items as $idx=>$it){$p=$it['p'];$sort=$idx+1;$stmt=$conn->prepare("INSERT INTO sale_items (business_id,branch_id,sale_id,product_id,item_name,hsn_code,quantity,gross_weight,stone_weight,net_weight,metal_rate,wastage_percent,wastage_amount,making_charge,stone_amount,other_charge,discount_amount,tax_percent,tax_amount,line_total,cost_amount,sort_order) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)");if(!$stmt)throw new Exception('Sale item prepare failed: '.$conn->error);$stmt->bind_param('iiiissdddddddddddddddi',$b,$br,$saleId,$p['id'],$p['product_name'],$p['hsn_code'],$it['qty'],$it['gross'],$it['stone_weight'],$it['net'],$it['rate'],$p['wastage_percent'],$it['waste'],$it['making'],$it['stone'],$it['other'],$it['disc'],$p['tax_percent'],$it['tax'],$it['total'],$it['cost'],$sort);if(!$stmt->execute())throw new Exception('Unable to save sale item: '.$stmt->error);$stmt->close();if((int)$p['track_stock']===1){$stmt=$conn->prepare('UPDATE product_stock SET quantity=quantity-?,gross_weight=GREATEST(gross_weight-?,0),net_weight=GREATEST(net_weight-?,0) WHERE business_id=? AND branch_id=? AND product_id=? AND quantity>=?');$stmt->bind_param('dddiiid',$it['qty'],$it['gross'],$it['net'],$b,$br,$p['id'],$it['qty']);if(!$stmt->execute()||$stmt->affected_rows<1)throw new Exception('Unable to update stock for '.$p['product_name']);$stmt->close();$remarks='Sale invoice '.$no;$stmt=$conn->prepare("INSERT INTO stock_movements (business_id,branch_id,product_id,movement_type,reference_table,reference_id,quantity_out,weight_out,rate,value_amount,remarks,created_by) VALUES (?,?,?,'Sale','sales',?,?,?,?,?,?,?)");$stmt->bind_param('iiiiddddsi',$b,$br,$p['id'],$saleId,$it['qty'],$it['net'],$it['rate'],$it['total'],$remarks,$u);if(!$stmt->execute())throw new Exception('Unable to add stock movement: '.$stmt->error);$stmt->close();}}
foreach($payRows as [$pm,$amount,$ref]){$stmt=$conn->prepare('INSERT INTO sale_payments (business_id,branch_id,sale_id,payment_method_id,amount,reference_no,created_by) VALUES (?,?,?,?,?,?,?)');$stmt->bind_param('iiiidsi',$b,$br,$saleId,$pm,$amount,$ref,$u);if(!$stmt->execute())throw new Exception('Unable to save payment: '.$stmt->error);$stmt->close();}audit($conn,$b,$br,$u,$saleId,$no);$conn->commit();respond(true,'Bill created successfully.',['sale_id'=>$saleId,'invoice_no'=>$no]);}catch(Throwable $e){$conn->rollback();respond(false,$e->getMessage(),[],500);}
