<?php
declare(strict_types=1);
if(session_status()===PHP_SESSION_NONE)session_start();date_default_timezone_set((string)($_SESSION['timezone']??'Asia/Kolkata'));
foreach([dirname(__DIR__).'/config/config.php',dirname(__DIR__).'/config.php',dirname(__DIR__).'/includes/config.php',dirname(__DIR__).'/super-admin/includes/config.php'] as $f){if(is_file($f)){require_once $f;break;}}
function respond(bool $ok,string $msg,array $x=[],int $code=200):void{http_response_code($code);header('Content-Type: application/json; charset=utf-8');echo json_encode(array_merge(['success'=>$ok,'message'=>$msg],$x),JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES);exit;}
if(!isset($conn)||!($conn instanceof mysqli))respond(false,'Database configuration is not available.',[],500);mysqli_report(MYSQLI_REPORT_OFF);$conn->set_charset('utf8mb4');
function tableExists(mysqli $c,string $t):bool{$s=$c->real_escape_string($t);$r=$c->query("SHOW TABLES LIKE '{$s}'");return $r&&$r->num_rows>0;}
function bindDyn(mysqli_stmt $s,string $types,array &$vals):void{if($types===''||!$vals)return;$p=[$types];foreach($vals as $k=>$v)$p[]=&$vals[$k];call_user_func_array([$s,'bind_param'],$p);}
if(empty($_SESSION['user_id']))respond(false,'Your session has expired. Please log in again.',[],401);$businessId=(int)($_SESSION['business_id']??0);$branchId=(int)($_SESSION['branch_id']??$_SESSION['default_branch_id']??0);if($businessId<=0)respond(false,'A valid business must be selected.',[],403);
foreach(['pawn_entries','pawn_customers','customers','pawn_categories'] as $t)if(!tableExists($conn,$t))respond(false,"Required table `{$t}` was not found.",[],500);
$action=strtolower(trim((string)($_GET['action']??'list')));
if($action==='bootstrap'){$sql="SELECT c.id,c.customer_name,c.customer_code FROM customers c INNER JOIN pawn_customers pc ON pc.customer_id=c.id AND pc.business_id=? WHERE c.business_id=?";if(tableExists($conn,'customers'))$sql.=" ORDER BY c.customer_name";$s=$conn->prepare($sql);if(!$s)respond(false,'Unable to prepare customer list: '.$conn->error,[],500);$s->bind_param('ii',$businessId,$businessId);$s->execute();$r=$s->get_result();$customers=[];while($r&&$row=$r->fetch_assoc()){$row['id']=(int)$row['id'];$customers[]=$row;}$s->close();respond(true,'Bootstrap loaded.',['customers'=>$customers,'defaults'=>['from_date'=>date('Y-m-01'),'to_date'=>date('Y-m-d')]]);}
$from=trim((string)($_GET['from_date']??date('Y-m-01')));$to=trim((string)($_GET['to_date']??date('Y-m-d')));$customerId=max(0,(int)($_GET['customer_id']??0));$status=trim((string)($_GET['status']??''));$search=trim((string)($_GET['search']??''));
$fd=DateTime::createFromFormat('Y-m-d',$from);$td=DateTime::createFromFormat('Y-m-d',$to);if(!$fd||!$td||$fd->format('Y-m-d')!==$from||$td->format('Y-m-d')!==$to)respond(false,'Enter valid report dates.',[],422);if($from>$to)[$from,$to]=[$to,$from];
$where=['pe.business_id=?','DATE(pe.pawn_date) BETWEEN ? AND ?'];$types='iss';$vals=[$businessId,$from,$to];if($branchId>0){$where[]='pe.branch_id=?';$types.='i';$vals[]=$branchId;}if($customerId>0){$where[]='pe.customer_id=?';$types.='i';$vals[]=$customerId;}if($status!==''){$where[]='pe.status=?';$types.='s';$vals[]=$status;}if($search!==''){$q='%'.$search.'%';$where[]='(pe.pawn_no LIKE ? OR c.customer_name LIKE ? OR c.mobile LIKE ? OR pc.category_name LIKE ?)';$types.='ssss';array_push($vals,$q,$q,$q,$q);}
$sql="SELECT pe.id,pe.pawn_no,pe.pawn_date,pe.principal_amount,pe.interest_percent,pe.interest_period,pe.due_date,pe.total_gross_weight,pe.total_net_weight,pe.total_interest_collected,pe.total_principal_paid,pe.balance_principal,pe.status,c.customer_name,c.customer_code,c.mobile,pc.category_name FROM pawn_entries pe LEFT JOIN customers c ON c.id=pe.customer_id LEFT JOIN pawn_categories pc ON pc.id=pe.pawn_category_id WHERE ".implode(' AND ',$where).' ORDER BY pe.pawn_date DESC,pe.id DESC';
$s=$conn->prepare($sql);if(!$s)respond(false,'Unable to prepare pawn report: '.$conn->error,[],500);bindDyn($s,$types,$vals);if(!$s->execute()){$e=$s->error;$s->close();respond(false,'Unable to load pawn report: '.$e,[],500);}$r=$s->get_result();$rows=[];$sum=['total_records'=>0,'principal_amount'=>0.0,'interest_collected'=>0.0,'principal_paid'=>0.0,'balance_principal'=>0.0,'gross_weight'=>0.0,'net_weight'=>0.0,'estimated_interest'=>0.0];
while($r&&$row=$r->fetch_assoc()){$row['id']=(int)$row['id'];foreach(['principal_amount','interest_percent','total_gross_weight','total_net_weight','total_interest_collected','total_principal_paid','balance_principal'] as $k)$row[$k]=(float)($row[$k]??0);$row['pawn_date_display']=date('d M Y',strtotime((string)$row['pawn_date']));$row['due_date_display']=!empty($row['due_date'])?date('d M Y',strtotime((string)$row['due_date'])):'—';$estimated=0.0;if($row['status']!=='Closed'&&$row['status']!=='Auctioned'&&$row['status']!=='Cancelled'){$days=max(0,(int)floor((time()-strtotime((string)$row['pawn_date']))/86400));if($row['interest_period']==='Daily')$estimated=$row['balance_principal']*$row['interest_percent']/100*$days;elseif($row['interest_period']==='Yearly')$estimated=$row['balance_principal']*$row['interest_percent']/100*($days/365);else $estimated=$row['balance_principal']*$row['interest_percent']/100*max(1,$days/30);} $row['estimated_interest']=round($estimated,2);$rows[]=$row;$sum['total_records']++;$sum['principal_amount']+=$row['principal_amount'];$sum['interest_collected']+=$row['total_interest_collected'];$sum['principal_paid']+=$row['total_principal_paid'];$sum['balance_principal']+=$row['balance_principal'];$sum['gross_weight']+=$row['total_gross_weight'];$sum['net_weight']+=$row['total_net_weight'];$sum['estimated_interest']+=$row['estimated_interest'];}$s->close();$period=['from_display'=>date('d-m-Y',strtotime($from)),'to_display'=>date('d-m-Y',strtotime($to))];
if($action==='export'){header('Content-Type: application/vnd.ms-excel; charset=utf-8');header('Content-Disposition: attachment; filename="pawn_report_'.date('Y-m-d_His').'.xls"');echo "Pawn Report\nPeriod\t{$period['from_display']} to {$period['to_display']}\n\nPawn No\tDate\tCustomer\tMobile\tCategory\tGross Wt\tNet Wt\tPrincipal\tInterest %\tInterest Paid\tPrincipal Paid\tBalance\tDue Date\tStatus\n";foreach($rows as $row)echo implode("\t",[$row['pawn_no'],$row['pawn_date_display'],$row['customer_name'],$row['mobile'],$row['category_name'],number_format($row['total_gross_weight'],3,'.',''),number_format($row['total_net_weight'],3,'.',''),number_format($row['principal_amount'],2,'.',''),number_format($row['interest_percent'],3,'.',''),number_format($row['total_interest_collected'],2,'.',''),number_format($row['total_principal_paid'],2,'.',''),number_format($row['balance_principal'],2,'.',''),$row['due_date_display'],$row['status']])."\n";exit;}
respond(true,'Pawn report loaded.',['rows'=>$rows,'summary'=>$sum,'period'=>$period]);
