<?php
if(session_status()===PHP_SESSION_NONE)session_start();
header('Content-Type: application/json; charset=utf-8');mysqli_report(MYSQLI_REPORT_OFF);ini_set('display_errors','0');
function out(bool$ok,string$msg,array$extra=[],int$code=200):void{http_response_code($code);echo json_encode(array_merge(['success'=>$ok,'message'=>$msg],$extra),JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES);exit;}
register_shutdown_function(static function(){if($e=error_get_last()){if(in_array($e['type'],[E_ERROR,E_PARSE,E_CORE_ERROR,E_COMPILE_ERROR],true))out(false,'Fatal API error: '.$e['message'],[],500);}});
foreach([dirname(__DIR__).'/config/config.php',dirname(__DIR__).'/config.php',dirname(__DIR__).'/includes/config.php',dirname(__DIR__).'/super-admin/includes/config.php']as$f){if(is_file($f)){require_once$f;break;}}
if(!isset($conn)||!($conn instanceof mysqli))out(false,'Database configuration is not available.',[],500);$conn->set_charset('utf8mb4');
if(empty($_SESSION['user_id']))out(false,'Session expired.',[],401);if($_SERVER['REQUEST_METHOD']!=='POST')out(false,'Invalid request method.',[],405);
if(!hash_equals((string)($_SESSION['pawn_customer_csrf']??''),(string)($_POST['csrf_token']??'')))out(false,'Invalid request token.',[],419);
function bindD(mysqli_stmt$s,string$t,array&$p):void{if(strlen($t)!==count($p))throw new RuntimeException('Bind mismatch');$b=[$t];foreach($p as$k=>$v)$b[]=&$p[$k];call_user_func_array([$s,'bind_param'],$b);}
function customerCode(mysqli$conn,int$b):string{$s=$conn->prepare("SELECT customer_code FROM customers WHERE business_id=? ORDER BY id DESC LIMIT 1");$s->bind_param('i',$b);$s->execute();$r=$s->get_result()->fetch_assoc();$s->close();$n=$r?((int)preg_replace('/\D/','',$r['customer_code'])+1):1;return'CUST'.str_pad((string)$n,4,'0',STR_PAD_LEFT);}
function uploadFile(string$input,string$folder,array$allowed,int$max,string$existing=''):string{if(!isset($_FILES[$input])||$_FILES[$input]['error']===UPLOAD_ERR_NO_FILE)return$existing;if($_FILES[$input]['error']!==UPLOAD_ERR_OK)throw new RuntimeException("Upload failed for {$input}.");if($_FILES[$input]['size']>$max)throw new RuntimeException("{$input} file is too large.");$fi=new finfo(FILEINFO_MIME_TYPE);$mime=$fi->file($_FILES[$input]['tmp_name']);if(!isset($allowed[$mime]))throw new RuntimeException("Invalid {$input} file type.");if(!is_dir($folder)&&!mkdir($folder,0775,true)&&!is_dir($folder))throw new RuntimeException('Unable to create upload folder.');$name=$input.'_'.bin2hex(random_bytes(10)).'.'.$allowed[$mime];if(!move_uploaded_file($_FILES[$input]['tmp_name'],$folder.$name))throw new RuntimeException("Unable to save {$input}.");return'uploads/pawn_customers/'.$name;}
$b=(int)($_SESSION['business_id']??0);$br=(int)($_SESSION['branch_id']??($_SESSION['default_branch_id']??0));$u=(int)($_SESSION['user_id']??0);if($b<=0||$br<=0)out(false,'Select business and branch.',[],403);$a=(string)($_POST['action']??'');
if($a==='options'){
 $customers=[];$s=$conn->prepare("SELECT id,customer_code,customer_name,mobile,email FROM customers WHERE business_id=? AND is_active=1 ORDER BY customer_name");$s->bind_param('i',$b);$s->execute();$r=$s->get_result();while($x=$r->fetch_assoc())$customers[]=$x;$s->close();$edit=null;$id=(int)($_POST['edit_id']??0);if($id>0){$s=$conn->prepare("SELECT pc.*,c.customer_name,c.customer_code,c.mobile,c.email,c.address_line1,c.address_line2,c.city,c.state,c.pincode,c.date_of_birth,c.anniversary_date FROM pawn_customers pc INNER JOIN customers c ON c.id=pc.customer_id WHERE pc.id=? AND pc.business_id=? LIMIT 1");$s->bind_param('ii',$id,$b);$s->execute();$edit=$s->get_result()->fetch_assoc();$s->close();}out(true,'Options loaded.',['customers'=>$customers,'customer'=>$edit]);
}
if($a==='save'){
 $editId=(int)($_POST['edit_id']??0);$customerId=(int)($_POST['customer_id']??0);$newName=trim((string)($_POST['customer_name_new']??''));if($customerId<=0&&$newName==='')out(false,'Select an existing customer or enter a new customer name.');
 $conn->begin_transaction();try{
  if($customerId<=0){$code=customerCode($conn,$b);$mobile=trim((string)($_POST['customer_mobile_new']??''));$email=trim((string)($_POST['customer_email_new']??''));$address=trim((string)($_POST['customer_address_new']??''));$city=trim((string)($_POST['customer_city_new']??''));$state=trim((string)($_POST['customer_state_new']??''));$pin=trim((string)($_POST['customer_pincode_new']??''));$dob=trim((string)($_POST['date_of_birth_new']??''));$ann=trim((string)($_POST['anniversary_date_new']??''));$dob=$dob!==''?$dob:null;$ann=$ann!==''?$ann:null;$s=$conn->prepare("INSERT INTO customers (business_id,customer_code,customer_type,customer_name,mobile,email,address_line1,city,state,pincode,date_of_birth,anniversary_date,is_active) VALUES (?,?,'PawnBroking',?,?,?,?,?,?,?,?,?,1)");$s->bind_param('issssssssss',$b,$code,$newName,$mobile,$email,$address,$city,$state,$pin,$dob,$ann);if(!$s->execute())throw new RuntimeException('Unable to create customer: '.$s->error);$customerId=(int)$s->insert_id;$s->close();}
  $existingPhoto=trim((string)($_POST['existing_photo']??''));$existingSignature=trim((string)($_POST['existing_signature']??''));$existingKyc=trim((string)($_POST['existing_kyc']??''));$folder=dirname(__DIR__).'/uploads/pawn_customers/';$photo=uploadFile('photo',$folder,['image/jpeg'=>'jpg','image/png'=>'png','image/webp'=>'webp'],5*1024*1024,$existingPhoto);$signature=uploadFile('signature',$folder,['image/jpeg'=>'jpg','image/png'=>'png','image/webp'=>'webp'],3*1024*1024,$existingSignature);$kycDoc=uploadFile('kyc_document',$folder,['image/jpeg'=>'jpg','image/png'=>'png','image/webp'=>'webp','application/pdf'=>'pdf'],8*1024*1024,$existingKyc);
  $guardian=trim((string)($_POST['guardian_name']??''));$occupation=trim((string)($_POST['occupation']??''));$income=max(0,(float)($_POST['annual_income']??0));$refName=trim((string)($_POST['reference_name']??''));$refMobile=trim((string)($_POST['reference_mobile']??''));$credit=max(0,(float)($_POST['credit_limit']??0));$risk=(string)($_POST['risk_category']??'Low');if(!in_array($risk,['Low','Medium','High'],true))$risk='Low';$notes=trim((string)($_POST['notes']??''));$kyc=isset($_POST['kyc_verified'])?1:0;
  if($editId>0){$s=$conn->prepare("UPDATE pawn_customers SET customer_id=?,guardian_name=?,occupation=?,annual_income=?,reference_name=?,reference_mobile=?,photo_path=?,signature_path=?,kyc_document_path=?,kyc_verified=?,credit_limit=?,risk_category=?,notes=? WHERE id=? AND business_id=?");$s->bind_param('issdsssssidssii',$customerId,$guardian,$occupation,$income,$refName,$refMobile,$photo,$signature,$kycDoc,$kyc,$credit,$risk,$notes,$editId,$b);if(!$s->execute())throw new RuntimeException('Unable to update pawn customer: '.$s->error);$saved=$editId;$s->close();}else{$s=$conn->prepare("SELECT id FROM pawn_customers WHERE business_id=? AND customer_id=? LIMIT 1");$s->bind_param('ii',$b,$customerId);$s->execute();$exists=$s->get_result()->fetch_assoc();$s->close();if($exists)throw new RuntimeException('This customer is already registered for pawn broking.');$s=$conn->prepare("INSERT INTO pawn_customers (business_id,customer_id,guardian_name,occupation,annual_income,reference_name,reference_mobile,photo_path,signature_path,kyc_document_path,kyc_verified,credit_limit,risk_category,notes,created_by) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)");$s->bind_param('iissdsssssidssi',$b,$customerId,$guardian,$occupation,$income,$refName,$refMobile,$photo,$signature,$kycDoc,$kyc,$credit,$risk,$notes,$u);if(!$s->execute())throw new RuntimeException('Unable to save pawn customer: '.$s->error);$saved=(int)$s->insert_id;$s->close();}$conn->commit();out(true,'Pawn customer saved successfully.',['pawn_customer_id'=>$saved]);}catch(Throwable$e){$conn->rollback();out(false,$e->getMessage(),[],500);}
}
if($a==='list'){
 $search=trim((string)($_POST['search']??''));$risk=trim((string)($_POST['risk']??''));$kyc=trim((string)($_POST['kyc']??''));$occupation=trim((string)($_POST['occupation']??''));$page=max(1,(int)($_POST['page']??1));$pp=max(5,min(100,(int)($_POST['per_page']??15)));$w=' WHERE pc.business_id=?';$t='i';$p=[$b];if($search!==''){$like='%'.$search.'%';$w.=" AND (c.customer_name LIKE ? OR c.customer_code LIKE ? OR c.mobile LIKE ? OR c.email LIKE ?)";$t.='ssss';array_push($p,$like,$like,$like,$like);}if($risk!==''){$w.=' AND pc.risk_category=?';$t.='s';$p[]=$risk;}if($kyc!==''){$w.=' AND pc.kyc_verified=?';$t.='i';$p[]=(int)$kyc;}if($occupation!==''){$w.=' AND pc.occupation=?';$t.='s';$p[]=$occupation;}
 $s=$conn->prepare("SELECT COUNT(*) total FROM pawn_customers pc INNER JOIN customers c ON c.id=pc.customer_id".$w);bindD($s,$t,$p);$s->execute();$total=(int)$s->get_result()->fetch_assoc()['total'];$s->close();$pages=max(1,(int)ceil($total/$pp));if($page>$pages)$page=$pages;$off=($page-1)*$pp;$lp=$p;$lp[]=$pp;$lp[]=$off;$lt=$t.'ii';$s=$conn->prepare("SELECT pc.*,c.customer_name,c.customer_code,c.mobile,c.email,(SELECT COUNT(*) FROM pawn_entries pe WHERE pe.business_id=pc.business_id AND pe.customer_id=pc.customer_id AND pe.status IN ('Active','Partially Paid')) active_loans FROM pawn_customers pc INNER JOIN customers c ON c.id=pc.customer_id {$w} ORDER BY c.customer_name LIMIT ? OFFSET ?");bindD($s,$lt,$lp);$s->execute();$r=$s->get_result();$rows=[];while($x=$r->fetch_assoc())$rows[]=$x;$s->close();$s=$conn->prepare("SELECT COUNT(*) total_customers,COALESCE(SUM(credit_limit),0) total_credit_limit,SUM(kyc_verified=1) kyc_verified_count,(SELECT COUNT(*) FROM pawn_entries pe WHERE pe.business_id=? AND pe.status IN ('Active','Partially Paid')) active_loans FROM pawn_customers WHERE business_id=?");$s->bind_param('ii',$b,$b);$s->execute();$stats=$s->get_result()->fetch_assoc();$s->close();$occ=[];$s=$conn->prepare("SELECT DISTINCT occupation FROM pawn_customers WHERE business_id=? AND occupation IS NOT NULL AND occupation<>'' ORDER BY occupation");$s->bind_param('i',$b);$s->execute();$r=$s->get_result();while($x=$r->fetch_assoc())$occ[]=$x['occupation'];$s->close();out(true,'Customers loaded.',['customers'=>$rows,'stats'=>$stats,'occupations'=>$occ,'meta'=>['page'=>$page,'total'=>$total,'total_pages'=>$pages,'from'=>$total?$off+1:0,'to'=>$total?min($off+$pp,$total):0]]);
}
if($a==='view'){
 $id=(int)($_POST['pawn_customer_id']??0);$s=$conn->prepare("SELECT pc.*,c.customer_name,c.customer_code,c.mobile,c.alternate_mobile,c.email,c.address_line1,c.address_line2,c.city,c.state,c.pincode,c.date_of_birth,c.anniversary_date FROM pawn_customers pc INNER JOIN customers c ON c.id=pc.customer_id WHERE pc.id=? AND pc.business_id=? LIMIT 1");$s->bind_param('ii',$id,$b);$s->execute();$c=$s->get_result()->fetch_assoc();$s->close();if(!$c)out(false,'Pawn customer not found.',[],404);$c['date_of_birth_display']=$c['date_of_birth']?date('d-m-Y',strtotime($c['date_of_birth'])):'';
 $cid=(int)$c['customer_id'];$s=$conn->prepare("SELECT COUNT(*) total_loans,SUM(status IN ('Active','Partially Paid')) active_loans,COALESCE(SUM(principal_amount),0) total_principal,COALESCE(SUM(balance_principal),0) total_outstanding FROM pawn_entries WHERE customer_id=? AND business_id=?");$s->bind_param('ii',$cid,$b);$s->execute();$summary=$s->get_result()->fetch_assoc();$s->close();$loans=[];$s=$conn->prepare("SELECT pe.*,pc.category_name FROM pawn_entries pe LEFT JOIN pawn_categories pc ON pc.id=pe.pawn_category_id WHERE pe.customer_id=? AND pe.business_id=? ORDER BY pe.id DESC LIMIT 10");$s->bind_param('ii',$cid,$b);$s->execute();$r=$s->get_result();while($x=$r->fetch_assoc()){$x['pawn_date_display']=date('d-m-Y',strtotime($x['pawn_date']));$loans[]=$x;}$s->close();$payments=[];$s=$conn->prepare("SELECT pp.*,pe.pawn_no FROM pawn_payments pp INNER JOIN pawn_entries pe ON pe.id=pp.pawn_entry_id WHERE pe.customer_id=? AND pp.business_id=? ORDER BY pp.payment_date DESC,pp.id DESC LIMIT 10");$s->bind_param('ii',$cid,$b);$s->execute();$r=$s->get_result();while($x=$r->fetch_assoc()){$x['payment_date_display']=date('d-m-Y',strtotime($x['payment_date']));$payments[]=$x;}$s->close();$ints=[];$s=$conn->prepare("SELECT pic.*,pe.pawn_no FROM pawn_interest_collections pic INNER JOIN pawn_entries pe ON pe.id=pic.pawn_entry_id WHERE pe.customer_id=? AND pic.business_id=? ORDER BY pic.collection_date DESC,pic.id DESC LIMIT 10");$s->bind_param('ii',$cid,$b);$s->execute();$r=$s->get_result();while($x=$r->fetch_assoc()){$x['collection_date_display']=date('d-m-Y',strtotime($x['collection_date']));$ints[]=$x;}$s->close();out(true,'Customer loaded.',['customer'=>$c,'summary'=>$summary,'loans'=>$loans,'payments'=>$payments,'interests'=>$ints]);
}
out(false,'Invalid action.',[],400);