<?php
if(session_status()===PHP_SESSION_NONE)session_start();header('Content-Type: application/json; charset=utf-8');mysqli_report(MYSQLI_REPORT_OFF);ini_set('display_errors','0');
function out(bool$ok,string$msg,array$extra=[],int$code=200):void{http_response_code($code);echo json_encode(array_merge(['success'=>$ok,'message'=>$msg],$extra),JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES);exit;}
register_shutdown_function(static function(){if($e=error_get_last()){if(in_array($e['type'],[E_ERROR,E_PARSE,E_CORE_ERROR,E_COMPILE_ERROR],true))out(false,'Fatal API error: '.$e['message'],[],500);}});
foreach([dirname(__DIR__).'/config/config.php',dirname(__DIR__).'/config.php',dirname(__DIR__).'/includes/config.php',dirname(__DIR__).'/super-admin/includes/config.php']as$f){if(is_file($f)){require_once$f;break;}}
if(!isset($conn)||!($conn instanceof mysqli))out(false,'Database configuration is not available.',[],500);$conn->set_charset('utf8mb4');if(empty($_SESSION['user_id']))out(false,'Session expired.',[],401);if($_SERVER['REQUEST_METHOD']!=='POST')out(false,'Invalid request method.',[],405);if(!hash_equals((string)($_SESSION['pawn_csrf']??''),(string)($_POST['csrf_token']??'')))out(false,'Invalid request token. Refresh the page.',[],419);
function tableExists(mysqli$c,string$t):bool{$s=$c->real_escape_string($t);$r=$c->query("SHOW TABLES LIKE '{$s}'");return$r&&$r->num_rows>0;}function hasCol(mysqli$c,string$t,string$x):bool{$t=$c->real_escape_string($t);$x=$c->real_escape_string($x);$r=$c->query("SHOW COLUMNS FROM `{$t}` LIKE '{$x}'");return$r&&$r->num_rows>0;}function bindD(mysqli_stmt$s,string$t,array&$p):void{if(strlen($t)!==count($p))throw new RuntimeException('Bind mismatch: '.strlen($t).' types, '.count($p).' values');$b=[$t];foreach($p as$k=>$v)$b[]=&$p[$k];call_user_func_array([$s,'bind_param'],$b);}function nextPawn(mysqli$c,int$b):string{$n=1;$s=$c->prepare('SELECT pawn_no FROM pawn_entries WHERE business_id=? ORDER BY id DESC LIMIT 1');if($s){$s->bind_param('i',$b);$s->execute();$r=$s->get_result()->fetch_assoc();$s->close();if($r)$n=(int)preg_replace('/\D/','',$r['pawn_no'])+1;}return'PN'.str_pad((string)$n,4,'0',STR_PAD_LEFT);}function audit(mysqli$c,int$b,int$br,int$u,int$id,string$no):void{if(!tableExists($c,'audit_logs'))return;$s=$c->prepare("INSERT INTO audit_logs (business_id,branch_id,user_id,module_code,action_type,reference_table,reference_id,description,new_values_json,ip_address,user_agent) VALUES (?,?,?,'pawn.entry','Create','pawn_entries',?,?,?,?,?)");if(!$s)return;$d='Created pawn entry '.$no;$j=json_encode(['pawn_no'=>$no]);$ip=(string)($_SERVER['REMOTE_ADDR']??'');$ua=(string)($_SERVER['HTTP_USER_AGENT']??'');$s->bind_param('iiiissss',$b,$br,$u,$id,$d,$j,$ip,$ua);$s->execute();$s->close();}
$b=(int)($_SESSION['business_id']??0);$br=(int)($_SESSION['branch_id']??($_SESSION['default_branch_id']??0));$u=(int)($_SESSION['user_id']??0);$a=(string)($_POST['action']??'');if($b<=0||$br<=0)out(false,'Select a valid business and branch.',[],403);if(!tableExists($conn,'pawn_entries')||!tableExists($conn,'pawn_items'))out(false,'Required pawn tables are missing.',[],500);
if($a==='options'){
 $customers=[];$sel=['id','customer_code','customer_name','mobile','email','address_line1','address_line2','city','state','pincode'];$sel[]=hasCol($conn,'customers','id_proof_type')?'id_proof_type':"'' AS id_proof_type";$sel[]=hasCol($conn,'customers','id_proof_number')?'id_proof_number':"'' AS id_proof_number";$s=$conn->prepare('SELECT '.implode(',',$sel).' FROM customers WHERE business_id=? AND is_active=1 ORDER BY customer_name');if($s){$s->bind_param('i',$b);$s->execute();$r=$s->get_result();while($x=$r->fetch_assoc())$customers[]=$x;$s->close();}
 $categories=[];$s=$conn->prepare("SELECT id,category_code,category_name,category_type,metal_type,purity_standard,default_interest_percent,max_loan_percent,valuation_method FROM pawn_categories WHERE business_id=? AND is_active=1 ORDER BY category_name");if($s){$s->bind_param('i',$b);$s->execute();$r=$s->get_result();while($x=$r->fetch_assoc())$categories[]=$x;$s->close();}
 $metals=[];if(tableExists($conn,'metals')){$s=$conn->prepare('SELECT id,metal_name FROM metals WHERE business_id=? AND is_active=1 ORDER BY metal_name');if($s){$s->bind_param('i',$b);$s->execute();$r=$s->get_result();while($x=$r->fetch_assoc())$metals[]=$x;$s->close();}}
 $rates=[];if(tableExists($conn,'metal_rates')){$cols=['rate_per_gram','purity'];$cols[]=hasCol($conn,'metal_rates','metal_id')?'metal_id':'NULL AS metal_id';$where=' WHERE business_id=?';if(hasCol($conn,'metal_rates','effective_date'))$where.=' AND effective_date<=CURDATE()';$s=$conn->prepare('SELECT '.implode(',',$cols).' FROM metal_rates'.$where.' ORDER BY id DESC');if($s){$s->bind_param('i',$b);$s->execute();$r=$s->get_result();$seen=[];while($x=$r->fetch_assoc()){$k=($x['metal_id']??'').'|'.strtolower((string)($x['purity']??''));if(!isset($seen[$k])){$seen[$k]=1;$rates[]=$x;}}$s->close();}}
 $methods=[];if(tableExists($conn,'payment_methods')){$s=$conn->prepare('SELECT id,method_name FROM payment_methods WHERE business_id=? AND is_active=1 ORDER BY method_name');if($s){$s->bind_param('i',$b);$s->execute();$r=$s->get_result();while($x=$r->fetch_assoc())$methods[]=$x;$s->close();}}
 out(true,'Options loaded.',['next_pawn_no'=>nextPawn($conn,$b),'customers'=>$customers,'categories'=>$categories,'metals'=>$metals,'metal_rates'=>$rates,'payment_methods'=>$methods]);
}
if($a==='create'){
 $date=trim((string)($_POST['pawn_date']??''));$cid=(int)($_POST['customer_id']??0);$cat=(int)($_POST['pawn_category_id']??0);$principal=max(0,(float)($_POST['principal_amount']??0));$interest=max(0,(float)($_POST['interest_percent']??0));$period=trim((string)($_POST['interest_period']??'Monthly'));$due=trim((string)($_POST['due_date']??''));$remarks=trim((string)($_POST['remarks']??''));$loanType=trim((string)($_POST['loan_type']??'General'));$method=trim((string)($_POST['interest_method']??'Simple'));$tenure=max(0,(int)($_POST['tenure_months']??0));$idType=trim((string)($_POST['id_proof_type']??''));$idNo=trim((string)($_POST['id_proof_number']??''));$ticket=max(0,(float)($_POST['ticket_charge']??0));$other=max(0,(float)($_POST['other_charge']??0));$pm=(int)($_POST['payment_method_id']??0);$pref=trim((string)($_POST['payment_reference']??''));
 if($date==='')out(false,'Pawn date is required.');if($cid<=0)out(false,'Select a customer.');if($cat<=0)out(false,'Select a pawn category.');if($principal<=0)out(false,'Principal amount must be greater than zero.');if(!in_array($period,['Monthly','Daily','Yearly'],true))out(false,'Invalid interest period.');if($tenure<=0)out(false,'Tenure months must be greater than zero.');
 $s=$conn->prepare('SELECT id FROM customers WHERE id=? AND business_id=? AND is_active=1 LIMIT 1');$s->bind_param('ii',$cid,$b);$s->execute();$customer=$s->get_result()->fetch_assoc();$s->close();if(!$customer)out(false,'Selected customer was not found.');$s=$conn->prepare('SELECT id FROM pawn_categories WHERE id=? AND business_id=? AND is_active=1 LIMIT 1');$s->bind_param('ii',$cat,$b);$s->execute();$category=$s->get_result()->fetch_assoc();$s->close();if(!$category)out(false,'Selected category was not found.');
 $mids=$_POST['metal_id']??[];$desc=$_POST['item_description']??[];$qtys=$_POST['quantity']??[];$pur=$_POST['purity']??[];$gross=$_POST['gross_weight']??[];$stone=$_POST['stone_weight']??[];$rates=$_POST['rate_per_gram']??[];$iremarks=$_POST['item_remarks']??[];$items=[];$tg=$ts=$tn=$te=0.0;foreach($desc as$i=>$d){$d=trim((string)$d);if($d==='')continue;$mid=(int)($mids[$i]??0);$q=max(1,(int)($qtys[$i]??1));$p=trim((string)($pur[$i]??''));$g=max(0,(float)($gross[$i]??0));$st=max(0,(float)($stone[$i]??0));$n=max(0,$g-$st);$rate=max(0,(float)($rates[$i]??0));$est=round($n*$rate,2);$ir=trim((string)($iremarks[$i]??''));if($mid<=0)out(false,'Select metal for every item.');if($g<=0)out(false,'Gross weight must be greater than zero.');if($st>$g)out(false,'Stone or less weight cannot exceed gross weight.');if($n<=0)out(false,'Net weight must be greater than zero.');$items[]=['mid'=>$mid,'d'=>$d,'q'=>$q,'p'=>$p,'g'=>$g,'s'=>$st,'n'=>$n,'r'=>$rate,'e'=>$est,'rm'=>$ir];$tg+=$g;$ts+=$st;$tn+=$n;$te+=$est;}if(!$items)out(false,'Add at least one valid pawn item.');
 $extras=['Loan Type: '.$loanType,'Interest Method: '.$method,'Tenure: '.$tenure.' month(s)'];if($idType!==''||$idNo!=='')$extras[]='ID Proof: '.trim($idType.' '.$idNo);if($ticket>0)$extras[]='Ticket Charge: ₹'.number_format($ticket,2);if($other>0)$extras[]='Other Charge: ₹'.number_format($other,2);if($pm>0)$extras[]='Disbursement Method ID: '.$pm;if($pref!=='')$extras[]='Disbursement Reference: '.$pref;foreach($items as$i=>$it)if($it['rm']!=='')$extras[]='Item '.($i+1).' Remark: '.$it['rm'];$final=trim(implode("\n",array_filter([$remarks,implode(' | ',$extras)])));
 $conn->begin_transaction();try{$no=nextPawn($conn,$b);$cols=['business_id','branch_id','pawn_no','pawn_date','customer_id','pawn_category_id','principal_amount','interest_percent','interest_period','total_gross_weight','total_net_weight','total_interest_collected','total_principal_paid','balance_principal','status','remarks','created_by'];$ph=array_fill(0,count($cols),'?');$types='iissiidddsddddssi';$vals=[$b,$br,$no,$date,$cid,$cat,$principal,$interest,$period,$tg,$tn,0.0,0.0,$principal,'Active',$final,$u];if($due!==''){$cols[]='due_date';$ph[]='?';$types.='s';$vals[]=$due;}$opt=['total_stone_weight'=>['d',$ts],'total_estimated_value'=>['d',$te],'loan_type'=>['s',$loanType],'interest_method'=>['s',$method],'tenure_months'=>['i',$tenure],'ticket_charge'=>['d',$ticket],'other_charge'=>['d',$other],'payment_method_id'=>['i',$pm>0?$pm:null],'payment_reference'=>['s',$pref]];foreach($opt as$c=>[$t,$v])if(hasCol($conn,'pawn_entries',$c)){$cols[]=$c;$ph[]='?';$types.=$t;$vals[]=$v;}if(hasCol($conn,'pawn_entries','created_at')){$cols[]='created_at';$ph[]='NOW()';}$s=$conn->prepare('INSERT INTO pawn_entries ('.implode(',',$cols).') VALUES ('.implode(',',$ph).')');if(!$s)throw new RuntimeException('Unable to prepare pawn entry: '.$conn->error);bindD($s,$types,$vals);if(!$s->execute())throw new RuntimeException('Unable to save pawn entry: '.$s->error);$pid=(int)$s->insert_id;$s->close();foreach($items as$it){$c=['business_id','pawn_entry_id','metal_id','item_description','quantity','gross_weight','stone_weight','net_weight','purity','estimated_value'];$p=array_fill(0,count($c),'?');$t='iiisidddsd';$v=[$b,$pid,$it['mid'],$it['d'],$it['q'],$it['g'],$it['s'],$it['n'],$it['p'],$it['e']];if(hasCol($conn,'pawn_items','rate_per_gram')){$c[]='rate_per_gram';$p[]='?';$t.='d';$v[]=$it['r'];}if(hasCol($conn,'pawn_items','remarks')){$c[]='remarks';$p[]='?';$t.='s';$v[]=$it['rm'];}if(hasCol($conn,'pawn_items','created_at')){$c[]='created_at';$p[]='NOW()';}$s=$conn->prepare('INSERT INTO pawn_items ('.implode(',',$c).') VALUES ('.implode(',',$p).')');if(!$s)throw new RuntimeException('Unable to prepare pawn item: '.$conn->error);bindD($s,$t,$v);if(!$s->execute())throw new RuntimeException('Unable to save pawn item: '.$s->error);$s->close();}audit($conn,$b,$br,$u,$pid,$no);$conn->commit();out(true,'Pawn entry created successfully. Pawn No: '.$no,['pawn_id'=>$pid,'pawn_no'=>$no]);}catch(Throwable$e){$conn->rollback();out(false,$e->getMessage(),[],500);}
}
out(false,'Invalid action.',[],400);
