<?php
session_start();
date_default_timezone_set('Asia/Kolkata');
require_once 'includes/config.php';
if (!isset($conn) || !($conn instanceof mysqli)) { die('Database connection not available. Check includes/config.php'); }
mysqli_report(MYSQLI_REPORT_OFF);
$conn->set_charset('utf8mb4');
if (!function_exists('h')) { function h($v): string { return htmlspecialchars((string)($v ?? ''), ENT_QUOTES, 'UTF-8'); } }
if (!function_exists('money')) { function money($v): string { return number_format((float)$v, 2); } }
if (!function_exists('tableExists')) { function tableExists(mysqli $conn, string $t): bool { $t=$conn->real_escape_string($t); $r=$conn->query("SHOW TABLES LIKE '{$t}'"); return $r && $r->num_rows>0; } }
if (!function_exists('nextNo')) { function nextNo(mysqli $conn, string $table, string $col, string $prefix, int $businessId): string { $like=$prefix.'%'; $sql="SELECT {$col} FROM {$table} WHERE business_id=? AND {$col} LIKE ? ORDER BY id DESC LIMIT 1"; $st=$conn->prepare($sql); if(!$st) return $prefix.'0001'; $st->bind_param('is',$businessId,$like); $st->execute(); $row=$st->get_result()->fetch_assoc(); $st->close(); $n=1; if($row){ $last=(string)$row[$col]; if(preg_match('/(\d+)$/',$last,$m)) $n=((int)$m[1])+1; } return $prefix.str_pad((string)$n,4,'0',STR_PAD_LEFT); } }
$userId=(int)($_SESSION['user_id']??0); $businessId=(int)($_SESSION['business_id']??1); if($userId<=0){ header('Location: ../login.php'); exit; }
$roleName = function_exists('currentRoleName') ? currentRoleName() : ($_SESSION['role_name'] ?? 'Admin');
if (!in_array($roleName, ['Super Admin','Admin','Manager','Billing'], true)) { die('Access denied.'); }

?>
<?php $currentPage='chit-collection'; $members=[]; $res=$conn->query("SELECT m.id,m.member_no,m.subscriber_name,g.group_name,g.installment_amount,g.id group_id FROM chit_members m INNER JOIN chit_groups g ON g.id=m.group_id WHERE m.business_id={$businessId} AND m.status='Active' ORDER BY m.subscriber_name"); if($res)while($r=$res->fetch_assoc())$members[]=$r; $payments=[]; $res=$conn->query("SELECT id,method_name FROM payment_methods WHERE is_active=1 ORDER BY method_name"); if($res)while($r=$res->fetch_assoc())$payments[]=$r; $member_id=(int)($_GET['member_id']??0);
if($_SERVER['REQUEST_METHOD']==='POST'){ $member_id=(int)$_POST['member_id']; $installment_id=(int)$_POST['installment_id']; $date=$_POST['collection_date']??date('Y-m-d'); $due=(float)$_POST['due_amount']; $paid=(float)$_POST['paid_amount']; $disc=(float)$_POST['discount_amount']; $pen=(float)$_POST['penalty_amount']; $net=$paid+$pen-$disc; $pm=($_POST['payment_method_id']!=='')?(int)$_POST['payment_method_id']:null; $ref=trim($_POST['reference_no']??''); $rem=trim($_POST['remarks']??''); $gid=0; foreach($members as $m){if((int)$m['id']===$member_id){$gid=(int)$m['group_id'];break;}} if($member_id<=0||$installment_id<=0||$paid<=0){$_SESSION['error']='Select member, installment and amount.';} else { $receipt=nextNo($conn,'chit_collections','receipt_no','CHR'.date('Ym'),$businessId); $st=$conn->prepare("INSERT INTO chit_collections (business_id,group_id,member_id,installment_id,receipt_no,collection_date,due_amount,paid_amount,discount_amount,penalty_amount,net_amount,payment_method_id,reference_no,remarks,created_by) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)"); $st->bind_param('iiiissdddddissi',$businessId,$gid,$member_id,$installment_id,$receipt,$date,$due,$paid,$disc,$pen,$net,$pm,$ref,$rem,$userId); }
}
?>

<?php if($_SERVER['REQUEST_METHOD']==='POST' && empty($_SESSION['error'])){ if($st->execute()){ $_SESSION['success']='Collection saved. Receipt: '.$receipt; $st->close(); header('Location: chit-ledger.php?member_id='.$member_id); exit; } else { $_SESSION['error']=$st->error; $st->close(); } } ?>

<!doctype html><html lang="en"><?php include('includes/head.php'); ?><body data-sidebar="dark"><?php include('includes/pre-loader.php'); ?><div id="layout-wrapper"><?php include('includes/topbar.php'); ?><div class="vertical-menu"><div data-simplebar class="h-100"><?php include('includes/sidebar.php'); ?></div></div><div class="main-content"><div class="page-content"><div class="container-fluid">
<?php if(isset($_SESSION['success'])): ?><div class="alert alert-success alert-dismissible fade show"><?php echo h($_SESSION['success']); unset($_SESSION['success']); ?><button type="button" class="btn-close" data-bs-dismiss="alert"></button></div><?php endif; ?>
<?php if(isset($_SESSION['error'])): ?><div class="alert alert-danger alert-dismissible fade show"><?php echo h($_SESSION['error']); unset($_SESSION['error']); ?><button type="button" class="btn-close" data-bs-dismiss="alert"></button></div><?php endif; ?>

<div class="card"><div class="card-body"><h4>Chit Collection</h4><form method="post" class="row g-3"><div class="col-md-4"><label>Member *</label><select name="member_id" id="member_id" class="form-select" required><option value="">Select</option><?php foreach($members as $m): ?><option value="<?php echo (int)$m['id']; ?>" data-amount="<?php echo (float)$m['installment_amount']; ?>" <?php echo $member_id===$m['id']?'selected':''; ?>><?php echo h($m['member_no'].' - '.$m['subscriber_name'].' - '.$m['group_name']); ?></option><?php endforeach; ?></select></div><div class="col-md-3"><label>Installment *</label><select name="installment_id" class="form-select" required><option value="">Select</option><?php $ins=$conn->query("SELECT ci.id,ci.installment_no,ci.due_date,g.group_name FROM chit_installments ci INNER JOIN chit_groups g ON g.id=ci.group_id WHERE ci.business_id={$businessId} AND ci.status='Open' ORDER BY ci.due_date"); if($ins)while($r=$ins->fetch_assoc()): ?><option value="<?php echo (int)$r['id']; ?>"><?php echo h($r['group_name'].' - #'.$r['installment_no'].' - '.date('d-m-Y',strtotime($r['due_date']))); ?></option><?php endwhile; ?></select></div><div class="col-md-2"><label>Date</label><input type="date" name="collection_date" class="form-control" value="<?php echo date('Y-m-d'); ?>"></div><div class="col-md-3"><label>Payment Method</label><select name="payment_method_id" class="form-select"><option value="">Select</option><?php foreach($payments as $p): ?><option value="<?php echo (int)$p['id']; ?>"><?php echo h($p['method_name']); ?></option><?php endforeach; ?></select></div><div class="col-md-2"><label>Due Amount</label><input type="number" step="0.01" name="due_amount" id="due_amount" class="form-control" value="0"></div><div class="col-md-2"><label>Paid Amount</label><input type="number" step="0.01" name="paid_amount" class="form-control" required></div><div class="col-md-2"><label>Discount</label><input type="number" step="0.01" name="discount_amount" class="form-control" value="0"></div><div class="col-md-2"><label>Penalty</label><input type="number" step="0.01" name="penalty_amount" class="form-control" value="0"></div><div class="col-md-4"><label>Reference</label><input name="reference_no" class="form-control"></div><div class="col-md-12"><label>Remarks</label><textarea name="remarks" class="form-control"></textarea></div><div><button class="btn btn-primary">Save Collection</button></div></form></div></div><script>document.getElementById('member_id').addEventListener('change',function(){let o=this.options[this.selectedIndex];document.getElementById('due_amount').value=o.dataset.amount||0;});</script>

</div></div><?php include('includes/footer.php'); ?></div></div><?php include('includes/rightbar.php'); ?><?php include('includes/scripts.php'); ?></body></html>
