<?php
session_start();
date_default_timezone_set('Asia/Kolkata');
require_once 'includes/config.php';
if (!isset($conn) || !($conn instanceof mysqli)) { die('Database connection not available. Check includes/config.php'); }
mysqli_report(MYSQLI_REPORT_OFF);
$conn->set_charset('utf8mb4');
if (!function_exists('h')) { function h($v): string { return htmlspecialchars((string)($v ?? ''), ENT_QUOTES, 'UTF-8'); } }
if (!function_exists('money')) { function money($v): string { return number_format((float)$v, 2); } }
if (!function_exists('tableExists')) { function tableExists(mysqli $conn, string $t): bool { $t=$conn->real_escape_string($t); $r=$conn->query("SHOW TABLES LIKE '{$t}'"); return $r && $r->num_rows>0; } }
if (!function_exists('nextNo')) { function nextNo(mysqli $conn, string $table, string $col, string $prefix, int $businessId): string { $like=$prefix.'%'; $sql="SELECT {$col} FROM {$table} WHERE business_id=? AND {$col} LIKE ? ORDER BY id DESC LIMIT 1"; $st=$conn->prepare($sql); if(!$st) return $prefix.'0001'; $st->bind_param('is',$businessId,$like); $st->execute(); $row=$st->get_result()->fetch_assoc(); $st->close(); $n=1; if($row){ $last=(string)$row[$col]; if(preg_match('/(\d+)$/',$last,$m)) $n=((int)$m[1])+1; } return $prefix.str_pad((string)$n,4,'0',STR_PAD_LEFT); } }
$userId=(int)($_SESSION['user_id']??0); $businessId=(int)($_SESSION['business_id']??1); if($userId<=0){ header('Location: ../login.php'); exit; }
$roleName = function_exists('currentRoleName') ? currentRoleName() : ($_SESSION['role_name'] ?? 'Admin');
if (!in_array($roleName, ['Super Admin','Admin','Manager','Billing'], true)) { die('Access denied.'); }

?>
<?php $currentPage='chit-members'; $groupId=(int)($_GET['group_id']??$_POST['group_id']??0); $groups=[]; $res=$conn->query("SELECT id, group_no, group_name FROM chit_groups WHERE business_id={$businessId} AND status='Active' ORDER BY group_name"); if($res)while($r=$res->fetch_assoc())$groups[]=$r; $customers=[]; $res=$conn->query("SELECT cc.id chit_customer_id,c.id customer_id,c.customer_name,c.mobile FROM chit_customers cc INNER JOIN customers c ON c.id=cc.customer_id WHERE cc.business_id={$businessId} ORDER BY c.customer_name"); if($res)while($r=$res->fetch_assoc())$customers[]=$r;
if($_SERVER['REQUEST_METHOD']==='POST'){ $groupId=(int)$_POST['group_id']; $chitCustomerId=(int)($_POST['chit_customer_id']??0); $name=trim($_POST['subscriber_name']??''); $mobile=trim($_POST['subscriber_mobile']??''); $join=$_POST['join_date']??date('Y-m-d'); $nom=trim($_POST['nominee_name']??''); $nmobile=trim($_POST['nominee_mobile']??''); $rel=trim($_POST['relation_name']??''); $sec=(float)($_POST['security_deposit']??0); $remarks=trim($_POST['remarks']??''); $customerId=null; if($chitCustomerId>0){ foreach($customers as $c){ if((int)$c['chit_customer_id']===$chitCustomerId){$customerId=(int)$c['customer_id']; if($name==='')$name=$c['customer_name']; if($mobile==='')$mobile=$c['mobile']; break;}} } if($groupId<=0||$name===''){$_SESSION['error']='Select group and member.';} else { $mno=nextNo($conn,'chit_members','member_no','MEM'.date('Ym'),$businessId); $st=$conn->prepare("INSERT INTO chit_members (business_id,group_id,member_no,customer_id,chit_customer_id,subscriber_name,subscriber_mobile,nominee_name,nominee_mobile,relation_name,join_date,security_deposit,status,remarks,created_by) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,'Active',?,?)"); $st->bind_param('iisiissssssdsi',$businessId,$groupId,$mno,$customerId,$chitCustomerId,$name,$mobile,$nom,$nmobile,$rel,$join,$sec,$remarks,$userId); if($st->execute()){ $st->close(); $conn->query("UPDATE chit_customers SET total_chits=total_chits+1, active_chits=active_chits+1 WHERE id=".(int)$chitCustomerId); $_SESSION['success']='Member added.'; header('Location: chit-members.php'); exit; } else $_SESSION['error']=$st->error; } } ?>

<!doctype html><html lang="en"><?php include('includes/head.php'); ?><body data-sidebar="dark"><?php include('includes/pre-loader.php'); ?><div id="layout-wrapper"><?php include('includes/topbar.php'); ?><div class="vertical-menu"><div data-simplebar class="h-100"><?php include('includes/sidebar.php'); ?></div></div><div class="main-content"><div class="page-content"><div class="container-fluid">
<?php if(isset($_SESSION['success'])): ?><div class="alert alert-success alert-dismissible fade show"><?php echo h($_SESSION['success']); unset($_SESSION['success']); ?><button type="button" class="btn-close" data-bs-dismiss="alert"></button></div><?php endif; ?>
<?php if(isset($_SESSION['error'])): ?><div class="alert alert-danger alert-dismissible fade show"><?php echo h($_SESSION['error']); unset($_SESSION['error']); ?><button type="button" class="btn-close" data-bs-dismiss="alert"></button></div><?php endif; ?>

<div class="card"><div class="card-body"><h4>Add Chit Member</h4><form method="post" class="row g-3"><div class="col-md-4"><label>Group *</label><select name="group_id" class="form-select" required><option value="">Select</option><?php foreach($groups as $g): ?><option value="<?php echo (int)$g['id']; ?>" <?php echo $groupId===$g['id']?'selected':''; ?>><?php echo h($g['group_no'].' - '.$g['group_name']); ?></option><?php endforeach; ?></select></div><div class="col-md-4"><label>Chit Customer</label><select name="chit_customer_id" class="form-select"><option value="">Manual Member</option><?php foreach($customers as $c): ?><option value="<?php echo (int)$c['chit_customer_id']; ?>"><?php echo h($c['customer_name'].' - '.$c['mobile']); ?></option><?php endforeach; ?></select></div><div class="col-md-4"><label>Join Date</label><input type="date" name="join_date" value="<?php echo date('Y-m-d'); ?>" class="form-control"></div><div class="col-md-4"><label>Subscriber Name *</label><input name="subscriber_name" class="form-control"></div><div class="col-md-4"><label>Mobile</label><input name="subscriber_mobile" class="form-control"></div><div class="col-md-4"><label>Security Deposit</label><input type="number" step="0.01" name="security_deposit" class="form-control" value="0"></div><div class="col-md-4"><label>Nominee</label><input name="nominee_name" class="form-control"></div><div class="col-md-4"><label>Nominee Mobile</label><input name="nominee_mobile" class="form-control"></div><div class="col-md-4"><label>Relation</label><input name="relation_name" class="form-control"></div><div class="col-md-12"><label>Remarks</label><textarea name="remarks" class="form-control"></textarea></div><div><button class="btn btn-primary">Save Member</button> <a href="chit-members.php" class="btn btn-secondary">Back</a></div></form></div></div>

</div></div><?php include('includes/footer.php'); ?></div></div><?php include('includes/rightbar.php'); ?><?php include('includes/scripts.php'); ?></body></html>
